"""Renders an IgPackageModel as a Python source file.

One module per FHIR IG package with nested CodeSystems, Profiles, Extensions, and
NamingSystems inner classes.

CodeSystems get URL constants (UPPER_SNAKE_CASE class attributes) and, when the
content is complete, an enum.Enum subclass with url(), coding(), from_value(), and
from_value_or_raise() helpers.

Extensions get a URL constant, a factory @staticmethod, and a getter @staticmethod
taking a _HasExtensions Protocol instance.

NamingSystems get a nested class per NamingSystem with type-keyed string attributes.
"""

from __future__ import annotations

from pathlib import Path

from .code_writer import CodeWriter
from .ig_package_model import ExtensionValueType, IgPackageModel
from .name_utils import to_pascal_case, to_snake_case

# FHIR primitive/complex type codes → (Python type name, Extension.value[x] field)
_PYTHON_TYPE_MAP: dict[str, tuple[str, str]] = {
    "string": ("str", "valueString"),
    "boolean": ("bool", "valueBoolean"),
    "integer": ("int", "valueInteger"),
    "decimal": ("float", "valueDecimal"),
    "dateTime": ("str", "valueDateTime"),
    "date": ("str", "valueDate"),
    "time": ("str", "valueTime"),
    "uri": ("str", "valueUri"),
    "url": ("str", "valueUrl"),
    "canonical": ("str", "valueCanonical"),
    "code": ("str", "valueCode"),
    "id": ("str", "valueId"),
    "markdown": ("str", "valueMarkdown"),
    "oid": ("str", "valueOid"),
    "uuid": ("str", "valueUuid"),
    "positiveInt": ("int", "valuePositiveInt"),
    "unsignedInt": ("int", "valueUnsignedInt"),
    "instant": ("str", "valueInstant"),
    "base64Binary": ("str", "valueBase64Binary"),
    # Complex FHIR types (require fhir.resources imports)
    "Coding": ("Coding", "valueCoding"),
    "CodeableConcept": ("CodeableConcept", "valueCodeableConcept"),
    "Reference": ("Reference", "valueReference"),
    "Quantity": ("Quantity", "valueQuantity"),
    "Identifier": ("Identifier", "valueIdentifier"),
    "Address": ("Address", "valueAddress"),
    "Period": ("Period", "valuePeriod"),
    "Range": ("Range", "valueRange"),
    "Ratio": ("Ratio", "valueRatio"),
    "HumanName": ("HumanName", "valueHumanName"),
    "Attachment": ("Attachment", "valueAttachment"),
    "ContactPoint": ("ContactPoint", "valueContactPoint"),
    "Annotation": ("Annotation", "valueAnnotation"),
    "Timing": ("Timing", "valueTiming"),
    "Age": ("Age", "valueAge"),
    "Count": ("Count", "valueCount"),
    "Distance": ("Distance", "valueDistance"),
    "Duration": ("Duration", "valueDuration"),
    "Money": ("Money", "valueMoney"),
    "SampledData": ("SampledData", "valueSampledData"),
    "Signature": ("Signature", "valueSignature"),
}

_PYTHON_BUILTINS: frozenset[str] = frozenset({"str", "bool", "int", "float"})


def generate(model: IgPackageModel, class_name: str) -> str:
    """Returns the generated Python source for the given model and class name."""
    w = CodeWriter()

    needs_enum = bool(model.code_system_concepts)
    needs_extensions = bool(model.extensions)
    fhir_imports = _collect_fhir_imports(model)
    bound_enum_names = _build_bound_enum_names(model)

    w.line(f"# Generated by ig-codegen from {model.package_name} {model.package_version}.")
    w.line("# Do not edit directly.")
    w.line("from __future__ import annotations")
    w.line()

    if needs_enum or needs_extensions:
        if needs_enum:
            w.line("import enum")
        typing_imports = []
        if needs_extensions:
            typing_imports.append("Protocol")
        if needs_enum:
            typing_imports.append("Self")
        w.line(f"from typing import {', '.join(sorted(typing_imports))}")
        w.line()

    for type_name in sorted(fhir_imports):
        w.line(f"from fhir.resources.{type_name.lower()} import {type_name}")
    if fhir_imports:
        w.line()

    if needs_extensions:
        w.block(
            "class _HasExtensions(Protocol)",
            lambda: w.line("extension: list[Extension] | None"),
        )
        w.line()

    def main_body() -> None:
        has_content = False
        if model.code_systems:
            _write_code_systems_class(w, model)
            has_content = True
        if model.profiles:
            if has_content:
                w.line()
            _write_profiles_class(w, model)
            has_content = True
        if model.extensions:
            if has_content:
                w.line()
            _write_extensions_class(w, model, class_name, bound_enum_names)
            has_content = True
        if model.naming_systems:
            if has_content:
                w.line()
            _write_naming_systems_class(w, model)
            has_content = True
        if not has_content:
            w.line("pass")

    w.block(f"class {class_name}", main_body)

    return str(w)


def write_to(model: IgPackageModel, class_name: str, output_dir: Path) -> Path:
    """Writes the generated source to the appropriate module file and returns the path."""
    source = generate(model, class_name)
    segments = model.package_name.split(".")
    module_dir = output_dir.joinpath(*segments)
    module_dir.mkdir(parents=True, exist_ok=True)

    current = output_dir
    for segment in segments:
        current = current / segment
        init = current / "__init__.py"
        if not init.exists():
            init.touch()

    module_file = module_dir / f"{segments[-1]}.py"
    module_file.write_text(source, encoding="utf-8")
    return module_file


# ── CodeSystems ──────────────────────────────────────────────────────────────


def _write_code_systems_class(w: CodeWriter, model: IgPackageModel) -> None:
    def body() -> None:
        first = True
        for constant_name, url in model.code_systems.items():
            if not first:
                w.line()
            first = False
            w.line(f'"""The canonical URL {url}."""') if False else None
            w.line(f'{constant_name} = "{_esc(url)}"')

        for constant_name, concepts in sorted(model.code_system_concepts.items()):
            enum_name = to_pascal_case(constant_name)
            system_url = model.code_systems[constant_name]
            w.line()
            _write_concept_enum(w, enum_name, system_url, concepts)

    w.block("class CodeSystems", body)


def _write_concept_enum(w: CodeWriter, enum_name: str, system_url: str, concepts) -> None:
    def body() -> None:
        w.line(f'"""Concepts for {system_url}."""')
        w.line()
        w.line("code: str")
        w.line("display: str | None")
        w.line()

        for concept in concepts:
            display_lit = f'"{_esc(concept.display)}"' if concept.display is not None else "None"
            w.line(f'{concept.constant_name} = ("{_esc(concept.code)}", {display_lit})')

        def init_body() -> None:
            w.line("self.code = code")
            w.line("self.display = display")

        w.line()
        w.block("def __init__(self, code: str, display: str | None) -> None", init_body)

        def url_body() -> None:
            w.line(f'return "{_esc(system_url)}"')

        w.line()
        w.block("def url(self) -> str", url_body)

        def coding_body() -> None:
            w.line("return Coding(system=self.url(), code=self.code, display=self.display)")

        w.line()
        w.block("def coding(self) -> Coding", coding_body)

        def from_value_body() -> None:
            def for_body() -> None:
                def if_body() -> None:
                    w.line("return member")

                w.block("if member.code == code", if_body)

            w.block("for member in cls", for_body)
            w.line("return None")

        w.line()
        w.line("@classmethod")
        w.block(
            "def from_value(cls, code: str) -> Self | None",
            from_value_body,
        )

        def from_value_or_raise_body() -> None:
            w.line("result = cls.from_value(code)")

            def if_body() -> None:
                w.line('raise ValueError(f"Unknown code: {code!r}")')

            w.block("if result is None", if_body)
            w.line("return result")

        w.line()
        w.line("@classmethod")
        w.block(
            "def from_value_or_raise(cls, code: str) -> Self",
            from_value_or_raise_body,
        )

    w.block(f"class {enum_name}(enum.Enum)", body)


# ── Profiles ─────────────────────────────────────────────────────────────────


def _write_profiles_class(w: CodeWriter, model: IgPackageModel) -> None:
    def body() -> None:
        first = True
        for constant_name, url in model.profiles.items():
            if not first:
                w.line()
            first = False
            w.line(f'{constant_name} = "{_esc(url)}"')

    w.block("class Profiles", body)


# ── Extensions ───────────────────────────────────────────────────────────────


def _write_extensions_class(
    w: CodeWriter,
    model: IgPackageModel,
    class_name: str,
    bound_enum_names: dict[str, str],
) -> None:
    def body() -> None:
        first = True
        for constant_name, url in model.extensions.items():
            if not first:
                w.line()
            first = False
            w.line(f'{constant_name} = "{_esc(url)}"')

        for constant_name, url in model.extensions.items():
            value_type = model.extension_value_types.get(constant_name, ExtensionValueType.NONE)
            method_name = to_snake_case(constant_name)
            w.line()
            _write_extension_factory(w, method_name, url, value_type, bound_enum_names, class_name)
            w.line()
            _write_extension_getter(w, method_name, url, value_type)

    w.block("class Extensions", body)


def _write_extension_factory(
    w: CodeWriter,
    method_name: str,
    url: str,
    value_type: ExtensionValueType,
    bound_enum_names: dict[str, str],
    class_name: str,
) -> None:
    if value_type.fhir_type_code is None:
        # Complex extension (NONE) or choice type (CHOICE) — no value parameter.
        def none_body() -> None:
            w.line(f'"""A new Extension for {url}."""')
            w.line(f'return Extension(url="{_esc(url)}")')

        w.line("@staticmethod")
        w.block(f"def {method_name}() -> Extension", none_body)
        return

    bound_enum = (
        bound_enum_names.get(value_type.bound_code_system_url)
        if value_type.bound_code_system_url
        else None
    )

    if bound_enum is not None:
        param_type = f"{class_name}.CodeSystems.{bound_enum}"
        if value_type.fhir_type_code == "CodeableConcept":

            def bound_cc_body() -> None:
                w.line(f'"""A new Extension for {url}."""')
                w.line(
                    f'return Extension(url="{_esc(url)}",'
                    f" valueCodeableConcept=CodeableConcept(coding=[value.coding()]))"
                )

            w.line("@staticmethod")
            w.block(f"def {method_name}(value: {param_type}) -> Extension", bound_cc_body)
        else:

            def bound_coding_body() -> None:
                w.line(f'"""A new Extension for {url}."""')
                w.line(f'return Extension(url="{_esc(url)}", valueCoding=value.coding())')

            w.line("@staticmethod")
            w.block(f"def {method_name}(value: {param_type}) -> Extension", bound_coding_body)
        return

    py_type, field_name = _python_type_for(value_type.fhir_type_code)

    def typed_body() -> None:
        w.line(f'"""A new Extension for {url}."""')
        w.line(f'return Extension(url="{_esc(url)}", {field_name}=value)')

    w.line("@staticmethod")
    w.block(f"def {method_name}(value: {py_type}) -> Extension", typed_body)


def _write_extension_getter(
    w: CodeWriter,
    method_name: str,
    url: str,
    value_type: ExtensionValueType,
) -> None:
    if value_type.fhir_type_code is not None and not value_type.choice:
        py_type, field_name = _python_type_for(value_type.fhir_type_code)
        return_type = f"{py_type} | None"

        def typed_getter_body() -> None:
            w.line(f'"""Gets the value of extension {url} from resource, or None if absent."""')

            def for_body() -> None:
                def if_body() -> None:
                    w.line(f"return ext.{field_name}")

                w.block(f'if ext.url == "{_esc(url)}"', if_body)

            w.block("for ext in resource.extension or []", for_body)
            w.line("return None")

        w.line("@staticmethod")
        w.block(
            f"def get_{method_name}(resource: _HasExtensions) -> {return_type}",
            typed_getter_body,
        )
    else:

        def ext_getter_body() -> None:
            w.line(f'"""Gets the extension {url} from resource, or None if absent."""')

            def for_body() -> None:
                def if_body() -> None:
                    w.line("return ext")

                w.block(f'if ext.url == "{_esc(url)}"', if_body)

            w.block("for ext in resource.extension or []", for_body)
            w.line("return None")

        w.line("@staticmethod")
        w.block(
            f"def get_{method_name}(resource: _HasExtensions) -> Extension | None",
            ext_getter_body,
        )


# ── NamingSystems ─────────────────────────────────────────────────────────────


def _write_naming_systems_class(w: CodeWriter, model: IgPackageModel) -> None:
    def body() -> None:
        first_ns = True
        for constant_name, entry in model.naming_systems.items():
            if not first_ns:
                w.line()
            first_ns = False
            ns_class_name = to_pascal_case(constant_name)

            def ns_body(entry=entry) -> None:
                if entry.description:
                    w.line(f'"""{_esc_docstring(entry.description)}"""')
                    w.line()
                first_type = True
                for type_code, values in entry.by_type.items():
                    if not first_type:
                        w.line()
                    first_type = False
                    attr_name = to_snake_case(type_code)
                    if len(values) == 1:
                        w.line(f'{attr_name} = "{_esc(values[0])}"')
                    else:
                        lits = ", ".join(f'"{_esc(v)}"' for v in values)
                        w.line(f"{attr_name} = [{lits}]")

            w.block(f"class {ns_class_name}", ns_body)

    w.block("class NamingSystems", body)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _collect_fhir_imports(model: IgPackageModel) -> set[str]:
    needed: set[str] = set()
    if model.code_system_concepts:
        needed.add("Coding")
    if model.extensions:
        needed.add("Extension")
        for value_type in model.extension_value_types.values():
            if value_type.fhir_type_code is not None and not value_type.choice:
                py_type, _ = _python_type_for(value_type.fhir_type_code)
                if py_type not in _PYTHON_BUILTINS:
                    needed.add(py_type)
    return needed


def _build_bound_enum_names(model: IgPackageModel) -> dict[str, str]:
    result: dict[str, str] = {}
    for constant_name in model.code_system_concepts:
        url = model.code_systems.get(constant_name)
        if url:
            result[url] = to_pascal_case(constant_name)
    return result


def _python_type_for(fhir_type_code: str) -> tuple[str, str]:
    entry = _PYTHON_TYPE_MAP.get(fhir_type_code)
    if entry:
        return entry
    # Unknown type: use fhir_type_code as-is (PascalCase complex type)
    return (fhir_type_code, f"value{fhir_type_code[0].upper()}{fhir_type_code[1:]}")


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _esc_docstring(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
