# Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.laborbefund 2026.0.3.
# Do not edit directly.
from __future__ import annotations

from typing import Protocol

from fhir.resources.coding import Coding
from fhir.resources.extension import Extension


class _HasExtensions(Protocol):
    extension: list[Extension] | None


class Laborbefund:
    class Profiles:
        MII_PR_LABOR_LABORANFORDERUNG = "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ServiceRequestLab|2026.0.3"

        MII_PR_LABOR_LABORBEFUND = "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/DiagnosticReportLab|2026.0.3"

        MII_PR_LABOR_LABORUNTERSUCHUNG = "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab|2026.0.3"

    class Extensions:
        MII_EX_LABOR_INTERPRETATIONSBEEINFLUSSENDE_EIGENSCHAFT = "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft"

        MII_EX_LABOR_QUELLE_KLINISCHES_BEZUGSDATUM = "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum"

        @staticmethod
        def mii_ex_labor_interpretationsbeeinflussende_eigenschaft(value: Coding) -> Extension:
            """A new Extension for https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft."""
            return Extension(url="https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft", valueCoding=value)

        @staticmethod
        def get_mii_ex_labor_interpretationsbeeinflussende_eigenschaft(resource: _HasExtensions) -> Coding | None:
            """Gets the value of extension https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft from resource, or None if absent."""
            for ext in resource.extension or []:
                if ext.url == "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft":
                    return ext.valueCoding
            return None

        @staticmethod
        def mii_ex_labor_quelle_klinisches_bezugsdatum(value: Coding) -> Extension:
            """A new Extension for https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum."""
            return Extension(url="https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum", valueCoding=value)

        @staticmethod
        def get_mii_ex_labor_quelle_klinisches_bezugsdatum(resource: _HasExtensions) -> Coding | None:
            """Gets the value of extension https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum from resource, or None if absent."""
            for ext in resource.extension or []:
                if ext.url == "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum":
                    return ext.valueCoding
            return None
