// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.icu 2026.0.2. Do not edit directly.
namespace De.Medizininformatikinitiative.Kerndatensatz.Icu;

public static class Icu
{
    public static class Profiles
    {
        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorische-sauerstofffraktion-eingestellt|2026.0.2</c>.
        /// </summary>
        public static string MiiIcuVentInspiratorischeSauerstofffraktionEingestellt => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorische-sauerstofffraktion-eingestellt|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanz => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-blutverlust|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrBlutverlust => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-blutverlust|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-drainage-generisch|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrDrainageGenerisch => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-drainage-generisch|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrFluessigkeitGesamt => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrGallenfluessigkeit => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-haemofiltration-einzelmesswerte|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrHaemofiltrationEinzelmesswerte => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-haemofiltration-einzelmesswerte|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-magensonde|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrMagensonde => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-magensonde|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-op-drainage|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrOpDrainage => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-op-drainage|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-pankreasdrainage|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrPankreasdrainage => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-pankreasdrainage|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-stuhlgang|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrStuhlgang => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-stuhlgang|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-urin|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrUrin => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-urin|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-wunddrainage|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzAusfuhrWunddrainage => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-wunddrainage|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzEinfuhrEnteraleFluessigkeit => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzEinfuhrFluessigkeitGesamt => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-tagesbilanz-fluessigkeit|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuBilanzTagesbilanzFluessigkeit => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-tagesbilanz-fluessigkeit|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-icu-device|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuDevice => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-icu-device|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-arterieller-druck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctArteriellerDruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-arterieller-druck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutfluss-cardiovasculaeres-geraet|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctBlutflussCardiovasculaeresGeraet => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutfluss-cardiovasculaeres-geraet|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutfluss-extrakorporaler-gasaustausch|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctBlutflussExtrakorporalerGasaustausch => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutfluss-extrakorporaler-gasaustausch|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutflussindex-extrakorporaler-gasaustausch|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctBlutflussindexExtrakorporalerGasaustausch => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutflussindex-extrakorporaler-gasaustausch|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dauer-extrakorporaler-gasaustausch|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctDauerExtrakorporalerGasaustausch => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dauer-extrakorporaler-gasaustausch|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dauer-haemodialysesitzung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctDauerHaemodialysesitzung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dauer-haemodialysesitzung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-extrakorporale-verfahren|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctDmEingestGemParameterExtrakorporaleVerfahren => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-extrakorporale-verfahren|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-extrakorporales-verfahren|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctExtrakorporalesVerfahren => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-extrakorporales-verfahren|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-gasfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctGasfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-gasfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-haemodialyse-blutfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctHaemodialyseBlutfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-haemodialyse-blutfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ionisiertes-kalzium-nierenersatzverfahren|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctOnisiertesKalziumNierenersatzverfahren => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ionisiertes-kalzium-nierenersatzverfahren|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-extrakorporalen-verfahren|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctParameterVonExtrakorporalenVerfahren => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-extrakorporalen-verfahren|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-substituatfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctSubstituatfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-substituatfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-substituatvolumen|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctSubstituatvolumen => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-substituatvolumen|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-venoeser-druck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEctVenoeserDruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-venoeser-druck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-exspiratorischer-sauerstoffpartialdruck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuEventXspiratorischerSauerstoffpartialdruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-exspiratorischer-sauerstoffpartialdruck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-arterieller-blutdruck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuMuvArteriellerBlutdruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-arterieller-blutdruck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-atemfrequenz|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuMuvAtemfrequenz => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-atemfrequenz|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-herzfrequenz|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuMuvHerzfrequenz => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-herzfrequenz|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuMuvKoerpergewicht => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuMuvKoerpergroesse => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-kopfumfang|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuMuvKopfumfang => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-kopfumfang|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemwegsdruck-bei-null-expiratorischem-gasfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentAtemwegsdruckBeiNullExpiratorischemGasfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemwegsdruck-bei-null-expiratorischem-gasfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentAtemwegsdruckMittleremExpiratorischemGasfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemzugvolumen-einstellung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentAtemzugvolumenEinstellung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemzugvolumen-einstellung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemzugvolumen-waehrend-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentAtemzugvolumenWaehrendBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemzugvolumen-waehrend-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungsvolumen-pro-minute-maschineller-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentBeatmungsvolumenMinMaschinellerBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungsvolumen-pro-minute-maschineller-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungszeit-hohem-druck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentBeatmungszeitHohemDruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungszeit-hohem-druck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungszeit-niedrigem-druck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentBeatmungszeitNiedrigemDruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungszeit-niedrigem-druck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentDmEingestellteGemesseneParameterBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-eingestellter-inspiratorischer-gasfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentEingestellterInspiratorischerGasfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-eingestellter-inspiratorischer-gasfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-einstellung-ausatmungszeit-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentEinstellungAusatmungszeitBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-einstellung-ausatmungszeit-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-einstellung-einatmungszeit-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentEinstellungEinatmungszeitBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-einstellung-einatmungszeit-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-endexpiratorischer-kohlendioxidpartialdruck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentEndexpiratorischerKohlendioxidpartialdruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-endexpiratorischer-kohlendioxidpartialdruck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-exspiratorischer-gasfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentExspiratorischerGasfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-exspiratorischer-gasfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-horowitz-in-arteriellem-blut|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentHorowitzInArteriellemBlut => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-horowitz-in-arteriellem-blut|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorische-sauerstofffraktion-gemessen|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentInspiratorischeSauerstofffraktionGemessen => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorische-sauerstofffraktion-gemessen|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorischer-gasfluss|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentInspiratorischerGasfluss => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorischer-gasfluss|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-maximaler-beatmungsdruck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentMaximalerBeatmungsdruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-maximaler-beatmungsdruck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-mechanische-atemfrequenz-beatmet|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentMechanischeAtemfrequenzBeatmet => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-mechanische-atemfrequenz-beatmet|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-mittlerer-beatmungsdruck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentMittlererBeatmungsdruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-mittlerer-beatmungsdruck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-positiv-endexpiratorischer-druck|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentPositivEndexpiratorischerDruck => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-positiv-endexpiratorischer-druck|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontane-atemfrequenz-beatmet|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentSpontaneAtemfrequenzBeatmet => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontane-atemfrequenz-beatmet|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontane-mechanische-atemfrequenz-beatmet|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentSpontaneMechanischeAtemfrequenzBeatmet => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontane-mechanische-atemfrequenz-beatmet|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontanes-atemzugvolumen|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentSpontanesAtemzugvolumen => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontanes-atemzugvolumen|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontanes-mechanisches-atemzugvolumen-waehrend-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentSpontanesPlusMechanischesAtemzugvolumen => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontanes-mechanisches-atemzugvolumen-waehrend-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-unterstuetzungsdruck-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentUnterstuezungsdruckBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-unterstuetzungsdruck-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-zeitverhaeltnis-ein-ausatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrIcuVentZeitverhaeltnisEinAusatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-zeitverhaeltnis-ein-ausatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dynamische-kompliance|2026.0.2</c>.
        /// </summary>
        public static string MiiPrVentIcuDynamischeKompliance => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dynamische-kompliance|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrVentIcuParameterVonBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-beatmung|2026.0.2";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-druckdifferenz-beatmung|2026.0.2</c>.
        /// </summary>
        public static string MiiPrVentProvidedIcuDruckdifferenzBeatmung => "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-druckdifferenz-beatmung|2026.0.2";
    }
}