// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.laborbefund 2026.0.3. Do not edit directly.
namespace De.Medizininformatikinitiative.Kerndatensatz.Laborbefund;

public static class Laborbefund
{
    public static class Profiles
    {
        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ServiceRequestLab|2026.0.3</c>.
        /// </summary>
        public static string MiiPrLaborLaboranforderung => "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ServiceRequestLab|2026.0.3";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/DiagnosticReportLab|2026.0.3</c>.
        /// </summary>
        public static string MiiPrLaborLaborbefund => "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/DiagnosticReportLab|2026.0.3";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab|2026.0.3</c>.
        /// </summary>
        public static string MiiPrLaborLaboruntersuchung => "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab|2026.0.3";
    }

    public static class Extensions
    {
        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft</c>.
        /// </summary>
        public static string MiiExLaborInterpretationsbeeinflussendeEigenschaft => "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum</c>.
        /// </summary>
        public static string MiiExLaborQuelleKlinischesBezugsdatum => "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum";
    }
}