// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.studie 2026.0.2. Do not edit directly.
using Hl7.Fhir.Model;

namespace De.Medizininformatikinitiative.Kerndatensatz.Studie;

public static class Studie
{
    public static class CodeSystems
    {
        public static class AssociatedPartyRoleCs
        {
            public const string Url = "http://example.org/fhir/CodeSystem/associated-party-role";

            public static Coding SPONSOR => new(Url, "sponsor", "Sponsor");

            public static Coding FUNDER => new(Url, "funder", "Funder");

            public static Coding PRINCIPAL_INVESTIGATOR => new(Url, "principal-investigator", "Principal Investigator");

            public static Coding CO_INVESTIGATOR => new(Url, "co-investigator", "Co-Investigator");

            public static Coding COORDINATOR => new(Url, "coordinator", "Study Coordinator");

            public static Coding PUBLISHER => new(Url, "publisher", "Publisher");

            public static Coding OTHER => new(Url, "other", "Other");

            private static IEnumerable<Coding> All => new[] { SPONSOR, FUNDER, PRINCIPAL_INVESTIGATOR, CO_INVESTIGATOR, COORDINATOR, PUBLISHER, OTHER };

            /// <summary>
            /// Looks up the constant whose <c>Code</c> equals <paramref name="code"/>.
            /// </summary>
            /// <param name="code">the FHIR code to look up</param>
            /// <returns>the matching <see cref="Coding"/></returns>
            /// <exception cref="ArgumentException">if no constant has that code</exception>
            public static Coding FromValue(string code) => All.FirstOrDefault(c => c.Code == code) ?? throw new ArgumentException($"Unknown code: {code}");
        }

        public static class ResearchStudyCategoryCs
        {
            public const string Url = "http://example.org/fhir/CodeSystem/research-study-category";

            public static Coding INTERVENTIONAL => new(Url, "interventional", "Interventional study");

            public static Coding OBSERVATIONAL => new(Url, "observational", "Observational study");

            public static Coding REGISTRY => new(Url, "registry", "Registry study");

            public static Coding OTHER => new(Url, "other", "Other");

            private static IEnumerable<Coding> All => new[] { INTERVENTIONAL, OBSERVATIONAL, REGISTRY, OTHER };

            /// <summary>
            /// Looks up the constant whose <c>Code</c> equals <paramref name="code"/>.
            /// </summary>
            /// <param name="code">the FHIR code to look up</param>
            /// <returns>the matching <see cref="Coding"/></returns>
            /// <exception cref="ArgumentException">if no constant has that code</exception>
            public static Coding FromValue(string code) => All.FirstOrDefault(c => c.Code == code) ?? throw new ArgumentException($"Unknown code: {code}");
        }
    }

    public static class Profiles
    {
        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-beteiligte-person|2026.0.1</c>.
        /// </summary>
        public static string MiiPrStudieBeteiligtePerson => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-beteiligte-person|2026.0.1";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-dokument|2026.0.1</c>.
        /// </summary>
        public static string MiiPrStudieDokument => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-dokument|2026.0.1";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-ein-auschluss-kriterium|2026.0.1</c>.
        /// </summary>
        public static string MiiPrStudieEinAuschlussKriterium => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-ein-auschluss-kriterium|2026.0.1";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-proband|2026.0.1</c>.
        /// </summary>
        public static string MiiPrStudieProband => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-proband|2026.0.1";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-register|2026.0.1</c>.
        /// </summary>
        public static string MiiPrStudieRegister => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-register|2026.0.1";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-studie|2026.0.1</c>.
        /// </summary>
        public static string MiiPrStudieStudie => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-studie|2026.0.1";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-studieneinschluss-anfrage|2026.0.1</c>.
        /// </summary>
        public static string MiiPrStudieStudieneinschlussAnfrage => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-studieneinschluss-anfrage|2026.0.1";
    }

    public static class Extensions
    {
        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-akronym</c>.
        /// </summary>
        public static string MiiExStudieAkronym => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-akronym";

        /// <summary>
        /// The canonical URL <c>http://hl7.org/fhir/5.0/StructureDefinition/extension-ResearchStudy.associatedParty</c>.
        /// </summary>
        public static string MiiExStudieBackportAssociatedParty => "http://hl7.org/fhir/5.0/StructureDefinition/extension-ResearchStudy.associatedParty";

        /// <summary>
        /// The canonical URL <c>http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionByCombination</c>.
        /// </summary>
        public static string MiiExStudieBackportDefinitionByCombination => "http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionByCombination";

        /// <summary>
        /// The canonical URL <c>http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionByTypeAndValue</c>.
        /// </summary>
        public static string MiiExStudieBackportDefinitionByTypeAndValue => "http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionByTypeAndValue";

        /// <summary>
        /// The canonical URL <c>http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionCanonical</c>.
        /// </summary>
        public static string MiiExStudieBackportDefinitionCanonical => "http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionCanonical";

        /// <summary>
        /// The canonical URL <c>http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionReference</c>.
        /// </summary>
        public static string MiiExStudieBackportDefinitionReference => "http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.definitionReference";

        /// <summary>
        /// The canonical URL <c>http://hl7.org/fhir/5.0/StructureDefinition/extension-ResearchStudy.label</c>.
        /// </summary>
        public static string MiiExStudieBackportLabel => "http://hl7.org/fhir/5.0/StructureDefinition/extension-ResearchStudy.label";

        /// <summary>
        /// The canonical URL <c>http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.linkId</c>.
        /// </summary>
        public static string MiiExStudieBackportLinkId => "http://hl7.org/fhir/5.0/StructureDefinition/extension-EvidenceVariable.characteristic.linkId";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-eligibility</c>.
        /// </summary>
        public static string MiiExStudieEligibility => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-eligibility";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-ethikvotum</c>.
        /// </summary>
        public static string MiiExStudieEthikvotum => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-ethikvotum";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-finanzierung</c>.
        /// </summary>
        public static string MiiExStudieFinanzierung => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-finanzierung";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-quell-register</c>.
        /// </summary>
        public static string MiiExStudieQuellRegister => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-quell-register";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-randomisierungsmethode</c>.
        /// </summary>
        public static string MiiExStudieRandomisierungsmethode => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-randomisierungsmethode";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-rekrutierung</c>.
        /// </summary>
        public static string MiiExStudieRekrutierung => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-rekrutierung";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-schlagwort</c>.
        /// </summary>
        public static string MiiExStudieSchlagwort => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-schlagwort";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-studienfokus</c>.
        /// </summary>
        public static string MiiExStudieStudienfokus => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-studienfokus";

        /// <summary>
        /// The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-studienregister</c>.
        /// </summary>
        public static string MiiExStudieStudienregister => "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-ex-studie-studienregister";
    }
}