// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.molgen 2026.0.4. Do not
// edit directly.
package de.medizininformatikinitiative.kerndatensatz.molgen;

import org.hl7.fhir.instance.model.api.IBaseHasExtensions;
import org.hl7.fhir.r4.model.CodeableConcept;
import org.hl7.fhir.r4.model.Coding;
import org.hl7.fhir.r4.model.Extension;
import org.hl7.fhir.r4.model.Reference;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

public final class Molgen {
  private Molgen() {}

  public static final class Profiles {
    private Profiles() {}

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/anforderung-genetischer-test|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/anforderung-genetischer-test|2026.0.4}
     */
    public static String miiPrMolgenAnforderungGenetischerTest() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/anforderung-genetischer-test|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/diagnostische-implikation|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/diagnostische-implikation|2026.0.4}
     */
    public static String miiPrMolgenDiagnostischeImplikation() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/diagnostische-implikation|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-folgemassnahme|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-folgemassnahme|2026.0.4}
     */
    public static String miiPrMolgenEmpfohleneFolgemassnahme() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-folgemassnahme|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/familienanamnese|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/familienanamnese|2026.0.4}
     */
    public static String miiPrMolgenFamilienanamnese() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/familienanamnese|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-genomic-study|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-genomic-study|2026.0.4}
     */
    public static String miiPrMolgenGenomicStudy() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-genomic-study|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-genomic-study-analysis|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-genomic-study-analysis|2026.0.4}
     */
    public static String miiPrMolgenGenomicStudyAnalysis() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-genomic-study-analysis|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/genotyp|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/genotyp|2026.0.4}
     */
    public static String miiPrMolgenGenotyp() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/genotyp|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/medikationsempfehlung|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/medikationsempfehlung|2026.0.4}
     */
    public static String miiPrMolgenMedikationsempfehlung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/medikationsempfehlung|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mikrosatelliteninstabilitaet|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mikrosatelliteninstabilitaet|2026.0.4}
     */
    public static String miiPrMolgenMikrosatelliteninstabilitaet() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mikrosatelliteninstabilitaet|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-molekularer-biomarker|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-molekularer-biomarker|2026.0.4}
     */
    public static String miiPrMolgenMolekularerBiomarker() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-molekularer-biomarker|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-molekulare-konsequenz|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-molekulare-konsequenz|2026.0.4}
     */
    public static String miiPrMolgenMolekulareKonsequenz() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-pr-molgen-molekulare-konsequenz|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/molekulargenetischer-befundbericht|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/molekulargenetischer-befundbericht|2026.0.4}
     */
    public static String miiPrMolgenMolekulargenetischerBefundbericht() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/molekulargenetischer-befundbericht|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mutationslast|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mutationslast|2026.0.4}
     */
    public static String miiPrMolgenMutationslast() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mutationslast|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/polygener-risiko-score|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/polygener-risiko-score|2026.0.4}
     */
    public static String miiPrMolgenPolygenerRisikoScore() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/polygener-risiko-score|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/therapeutische-implikation|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/therapeutische-implikation|2026.0.4}
     */
    public static String miiPrMolgenTherapeutischeImplikation() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/therapeutische-implikation|2026.0.4";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/variante|2026.0.4}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/variante|2026.0.4}
     */
    public static String miiPrMolgenVariante() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/variante|2026.0.4";
    }
  }

  public static final class Extensions {
    private Extensions() {}

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-massnahme}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-massnahme}
     *     and the given value
     */
    public static @NonNull Extension miiExMolgenEmpfohleneMassnahme(@NonNull Reference value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-massnahme",
          value);
    }

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-familiare-linie}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-familiare-linie}
     *     and the given value
     */
    public static @NonNull Extension miiExMolgenFamiliareLinie(@NonNull Coding value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-familiare-linie",
          value);
    }

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/risk-assessment-einflussfaktor}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/risk-assessment-einflussfaktor}
     *     and the given value
     */
    public static @NonNull Extension miiExMolgenRiskAssessmentEinflussfaktor(
        @NonNull CodeableConcept value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/risk-assessment-einflussfaktor",
          value);
    }

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsgrad}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsgrad}
     *     and the given value
     */
    public static @NonNull Extension miiExMolgenVerwandtschaftsgrad(@NonNull Coding value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsgrad",
          value);
    }

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsverhaeltnis}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsverhaeltnis}
     *     and the given value
     */
    public static @NonNull Extension miiExMolgenVerwandtschaftsverhaeltnis(@NonNull Coding value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsverhaeltnis",
          value);
    }

    /**
     * Gets the value of extension {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-massnahme}
     * from {@code resource}, or {@code null} if absent.
     *
     * @param resource the resource or element to read from
     * @return the extension value, or {@code null}
     */
    public static @Nullable Reference getMiiExMolgenEmpfohleneMassnahme(
        @NonNull IBaseHasExtensions resource) {
      for (var e : resource.getExtension()) {
        if ("https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-massnahme"
            .equals(e.getUrl())) {
          return (Reference) ((Extension) e).getValue();
        }
      }
      return null;
    }

    /**
     * Gets the value of extension {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-familiare-linie}
     * from {@code resource}, or {@code null} if absent.
     *
     * @param resource the resource or element to read from
     * @return the extension value, or {@code null}
     */
    public static @Nullable Coding getMiiExMolgenFamiliareLinie(
        @NonNull IBaseHasExtensions resource) {
      for (var e : resource.getExtension()) {
        if ("https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-familiare-linie"
            .equals(e.getUrl())) {
          return (Coding) ((Extension) e).getValue();
        }
      }
      return null;
    }

    /**
     * Gets the value of extension {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/risk-assessment-einflussfaktor}
     * from {@code resource}, or {@code null} if absent.
     *
     * @param resource the resource or element to read from
     * @return the extension value, or {@code null}
     */
    public static @Nullable CodeableConcept getMiiExMolgenRiskAssessmentEinflussfaktor(
        @NonNull IBaseHasExtensions resource) {
      for (var e : resource.getExtension()) {
        if ("https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/risk-assessment-einflussfaktor"
            .equals(e.getUrl())) {
          return (CodeableConcept) ((Extension) e).getValue();
        }
      }
      return null;
    }

    /**
     * Gets the value of extension {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsgrad}
     * from {@code resource}, or {@code null} if absent.
     *
     * @param resource the resource or element to read from
     * @return the extension value, or {@code null}
     */
    public static @Nullable Coding getMiiExMolgenVerwandtschaftsgrad(
        @NonNull IBaseHasExtensions resource) {
      for (var e : resource.getExtension()) {
        if ("https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsgrad"
            .equals(e.getUrl())) {
          return (Coding) ((Extension) e).getValue();
        }
      }
      return null;
    }

    /**
     * Gets the value of extension {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsverhaeltnis}
     * from {@code resource}, or {@code null} if absent.
     *
     * @param resource the resource or element to read from
     * @return the extension value, or {@code null}
     */
    public static @Nullable Coding getMiiExMolgenVerwandtschaftsverhaeltnis(
        @NonNull IBaseHasExtensions resource) {
      for (var e : resource.getExtension()) {
        if ("https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsverhaeltnis"
            .equals(e.getUrl())) {
          return (Coding) ((Extension) e).getValue();
        }
      }
      return null;
    }

    public static final class Urls {
      private Urls() {}

      /**
       * @return the extension URL {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-massnahme}
       */
      public static @NonNull String miiExMolgenEmpfohleneMassnahme() {
        return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/empfohlene-massnahme";
      }

      /**
       * @return the extension URL {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-familiare-linie}
       */
      public static @NonNull String miiExMolgenFamiliareLinie() {
        return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-familiare-linie";
      }

      /**
       * @return the extension URL {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/risk-assessment-einflussfaktor}
       */
      public static @NonNull String miiExMolgenRiskAssessmentEinflussfaktor() {
        return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/risk-assessment-einflussfaktor";
      }

      /**
       * @return the extension URL {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsgrad}
       */
      public static @NonNull String miiExMolgenVerwandtschaftsgrad() {
        return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsgrad";
      }

      /**
       * @return the extension URL {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsverhaeltnis}
       */
      public static @NonNull String miiExMolgenVerwandtschaftsverhaeltnis() {
        return "https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen/StructureDefinition/mii-ex-molgen-verwandtschaftsverhaeltnis";
      }
    }
  }
}
