// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.laborbefund 2026.0.3.
// Do not edit directly.
package de.medizininformatikinitiative.kerndatensatz.laborbefund;

public final class Laborbefund {
  private Laborbefund() {}

  public static final class Profiles {
    private Profiles() {}

    public static String miiPrLaborLaboranforderung() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ServiceRequestLab|2026.0.3";
    }

    public static String miiPrLaborLaborbefund() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/DiagnosticReportLab|2026.0.3";
    }

    public static String miiPrLaborLaboruntersuchung() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab|2026.0.3";
    }
  }

  public static final class Extensions {
    private Extensions() {}

    public static String miiExLaborInterpretationsbeeinflussendeEigenschaft() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/InterpretationsbeeinflussendeEigenschaft";
    }

    public static String miiExLaborQuelleKlinischesBezugsdatum() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum";
    }
  }
}
