using System.Text;

namespace IgCodegen;

/// <summary>
/// Renders an <see cref="IgPackageModel"/> as a C# source file: one static class per package with
/// nested <c>CodeSystems</c>, <c>Profiles</c>, and <c>Extensions</c> inner classes.
///
/// <para>CodeSystems and Profiles each get one static no-arg URL accessor per canonical URL, placed
/// inside a nested <c>Urls</c> class to avoid naming collisions with the enum types that share the
/// same PascalCase name.</para>
///
/// <para>A CodeSystem that ships its own concepts inline (<c>content == "complete"</c>) additionally
/// gets a nested <c>enum</c> and a top-level extension method class (C# extension methods cannot live
/// in nested classes) providing <c>Url()</c>, <c>Code()</c>, <c>Display()</c>, <c>Coding()</c>,
/// <c>FromValue()</c>, and <c>FromValueOrThrow()</c>.</para>
///
/// <para>Extensions get a static factory method per canonical URL returning a Firely
/// <c>Hl7.Fhir.Model.Extension</c> missing only the value.</para>
/// </summary>
public static class CSharpConstantsGenerator
{
    // FHIR type codes (as they appear in StructureDefinition JSON) mapped to their Firely SDK
    // class names. Lowercase-first entries are FHIR primitives; PascalCase entries are complex
    // types whose Firely name differs from the FHIR name (e.g. Reference → ResourceReference).
    private static readonly IReadOnlyDictionary<string, string> FirelyTypeMap = new Dictionary<
        string,
        string
    >(StringComparer.Ordinal)
    {
        // Primitives — FHIR name → Firely Fhir* wrapper class
        ["string"] = "FhirString",
        ["boolean"] = "FhirBoolean",
        ["integer"] = "FhirInteger",
        ["decimal"] = "FhirDecimal",
        ["dateTime"] = "FhirDateTime",
        ["date"] = "Date",
        ["time"] = "Time",
        ["uri"] = "FhirUri",
        ["url"] = "FhirUrl",
        ["canonical"] = "Canonical",
        ["code"] = "Code",
        ["id"] = "Id",
        ["markdown"] = "Markdown",
        ["oid"] = "Oid",
        ["uuid"] = "Uuid",
        ["positiveInt"] = "PositiveInt",
        ["unsignedInt"] = "UnsignedInt",
        ["instant"] = "Instant",
        ["base64Binary"] = "Base64Binary",
        // Complex types that Firely renames
        ["Reference"] = "ResourceReference",
    };

    public static string Generate(IgPackageModel model, string csharpNamespace, string className)
    {
        var w = new CodeWriter();

        w.Line(
            $"// Generated by ig-codegen from {model.PackageName} {model.PackageVersion}. Do not edit directly."
        );

        bool needsFhir = model.CodeSystemConcepts.Count > 0 || model.Extensions.Count > 0;
        if (needsFhir)
        {
            w.Line("using Hl7.Fhir.Model;");
        }
        w.Line();
        w.Line($"namespace {csharpNamespace};");
        w.Line();

        w.Line($"public static class {className}");
        w.Block(() =>
        {
            WriteCodeSystemsClass(w, className, model);
            WriteProfilesClass(w, model);
            WriteExtensionsClass(w, className, model);
            WriteNamingSystemsClass(w, model);
        });

        // Extension method classes must be at namespace level in C#.
        foreach (var (constantName, concepts) in model.CodeSystemConcepts)
        {
            string enumName = NameUtils.ToPascalCase(constantName);
            string systemUrl = model.CodeSystems[constantName];
            w.Line();
            WriteEnumExtensionClass(w, className, enumName, systemUrl, concepts);
        }

        return w.ToString();
    }

    public static string WriteTo(
        IgPackageModel model,
        string csharpNamespace,
        string className,
        string outputDir
    )
    {
        string source = Generate(model, csharpNamespace, className);
        string namespacePath = csharpNamespace.Replace('.', Path.DirectorySeparatorChar);
        string dir = Path.Combine(outputDir, namespacePath);
        Directory.CreateDirectory(dir);
        string path = Path.Combine(dir, $"{className}.cs");
        File.WriteAllText(path, source, Encoding.UTF8);
        return path;
    }

    // ── CodeSystems ──────────────────────────────────────────────────────────

    private static void WriteCodeSystemsClass(CodeWriter w, string className, IgPackageModel model)
    {
        if (model.CodeSystems.Count == 0)
            return;

        w.Line("public static class CodeSystems");
        w.Block(() =>
        {
            // Nested Urls class holds the URL properties. This avoids a name clash between e.g.
            // the MiiCsOnkoIntention property and the MiiCsOnkoIntention enum in the same type.
            w.Line("public static class Urls");
            w.Block(() =>
            {
                foreach (var (constantName, url) in model.CodeSystems)
                {
                    string propertyName = NameUtils.ToPascalCase(constantName);
                    w.Line($"/// <summary>The canonical URL <c>{url}</c>.</summary>");
                    w.Line($"public static string {propertyName} =>");
                    w.Indent(() => w.Line($"\"{url}\";"));
                    w.Line();
                }
            });

            foreach (var (constantName, concepts) in model.CodeSystemConcepts)
            {
                string enumName = NameUtils.ToPascalCase(constantName);
                string systemUrl = model.CodeSystems[constantName];
                w.Line();
                WriteConceptEnum(w, enumName, systemUrl, concepts);
            }
        });
    }

    private static void WriteConceptEnum(
        CodeWriter w,
        string enumName,
        string systemUrl,
        IReadOnlyList<ConceptConstant> concepts
    )
    {
        w.Line($"/// <summary>Concepts for <c>{systemUrl}</c>.</summary>");
        w.Line($"public enum {enumName}");
        w.Block(() =>
        {
            foreach (var concept in concepts)
            {
                if (concept.Display is not null)
                    w.Line(
                        $"/// <summary><c>{XmlEscape(concept.Code)}</c> - {XmlEscape(concept.Display)}</summary>"
                    );
                else
                    w.Line($"/// <summary><c>{XmlEscape(concept.Code)}</c></summary>");
                w.Line($"{concept.ConstantName},");
            }
        });
    }

    // ── Profiles ─────────────────────────────────────────────────────────────

    private static void WriteProfilesClass(CodeWriter w, IgPackageModel model)
    {
        if (model.Profiles.Count == 0)
            return;

        w.Line();
        w.Line("public static class Profiles");
        w.Block(() =>
        {
            foreach (var (constantName, url) in model.Profiles)
            {
                string propertyName = NameUtils.ToPascalCase(constantName);
                w.Line($"/// <summary>The canonical URL <c>{url}</c>.</summary>");
                w.Line($"public static string {propertyName} => \"{url}\";");
                w.Line();
            }
        });
    }

    // ── Extensions ───────────────────────────────────────────────────────────

    private static void WriteExtensionsClass(CodeWriter w, string className, IgPackageModel model)
    {
        if (model.Extensions.Count == 0)
            return;

        var boundEnumNames = BuildBoundEnumNames(model);

        w.Line();
        w.Line("public static class Extensions");
        w.Block(() =>
        {
            foreach (var (constantName, url) in model.Extensions)
            {
                string methodName = NameUtils.ToPascalCase(constantName);
                var valueType = model.ExtensionValueTypes.GetValueOrDefault(
                    constantName,
                    ExtensionValueType.None
                );
                WriteExtensionFactory(w, className, methodName, url, valueType, boundEnumNames);
                w.Line();
            }
        });
    }

    private static void WriteExtensionFactory(
        CodeWriter w,
        string className,
        string methodName,
        string url,
        ExtensionValueType valueType,
        IReadOnlyDictionary<string, string> boundEnumNames
    )
    {
        if (valueType.FhirTypeCode is null && !valueType.Choice)
        {
            // Complex extension with no value[x] of its own.
            w.Line($"/// <summary>");
            w.Line($"/// A new, empty <see cref=\"Extension\"/> for <c>{url}</c>, for further");
            w.Line(
                $"/// population with nested extensions via <see cref=\"Extension.AddExtension\"/>."
            );
            w.Line($"/// </summary>");
            w.Line(
                $"/// <returns>A new <see cref=\"Extension\"/> with url <c>{url}</c> and no value.</returns>"
            );
            w.Line($"public static Extension {methodName}() =>");
            w.Indent(() => w.Line($"new() {{ Url = \"{url}\" }};"));
            return;
        }

        string? boundEnumName = valueType.BoundCodeSystemUrl is not null
            ? boundEnumNames.GetValueOrDefault(valueType.BoundCodeSystemUrl)
            : null;

        if (boundEnumName is not null)
        {
            WriteBoundCodingExtensionFactory(
                w,
                className,
                methodName,
                url,
                valueType.FhirTypeCode!,
                boundEnumName
            );
            return;
        }

        string paramTypeName = valueType.Choice
            ? "DataType"
            : FirelyTypeFor(valueType.FhirTypeCode!);

        w.Line($"/// <summary>A new <see cref=\"Extension\"/> for <c>{url}</c>.</summary>");
        w.Line($"/// <param name=\"value\">The extension value.</param>");
        w.Line(
            $"/// <returns>A new <see cref=\"Extension\"/> with url <c>{url}</c> and the given value.</returns>"
        );
        w.Line($"public static Extension {methodName}({paramTypeName} value) =>");
        w.Indent(() => w.Line($"new(\"{url}\", value);"));
    }

    private static void WriteBoundCodingExtensionFactory(
        CodeWriter w,
        string className,
        string methodName,
        string url,
        string fhirTypeCode,
        string boundEnumName
    )
    {
        w.Line($"/// <summary>A new <see cref=\"Extension\"/> for <c>{url}</c>.</summary>");
        w.Line(
            $"/// <param name=\"value\">The extension value, as a <c>{boundEnumName}</c> concept.</param>"
        );
        w.Line(
            $"/// <returns>A new <see cref=\"Extension\"/> with url <c>{url}</c> and the given value.</returns>"
        );
        w.Line($"public static Extension {methodName}(CodeSystems.{boundEnumName} value) =>");
        if (fhirTypeCode == "CodeableConcept")
        {
            w.Indent(() =>
                w.Line(
                    $"new(\"{url}\", new CodeableConcept(value.Url(), value.Code(), value.Display()));"
                )
            );
        }
        else
        {
            w.Indent(() => w.Line($"new(\"{url}\", value.Coding());"));
        }
    }

    // ── Per-enum extension method class ──────────────────────────────────────

    private static void WriteEnumExtensionClass(
        CodeWriter w,
        string className,
        string enumName,
        string systemUrl,
        IReadOnlyList<ConceptConstant> concepts
    )
    {
        string qualifiedEnum = $"{className}.CodeSystems.{enumName}";

        w.Line($"/// <summary>Extension methods for <see cref=\"{qualifiedEnum}\"/>.</summary>");
        w.Line($"public static class {enumName}Extensions");
        w.Block(() =>
        {
            // Url()
            w.Line($"/// <returns>The CodeSystem URL <c>{systemUrl}</c>.</returns>");
            w.Line($"public static string Url(this {qualifiedEnum} _) =>");
            w.Indent(() => w.Line($"\"{systemUrl}\";"));
            w.Line();

            // Code()
            w.Line("/// <returns>The FHIR code for this concept.</returns>");
            w.Line($"public static string Code(this {qualifiedEnum} value) => value switch");
            w.Block(
                () =>
                {
                    foreach (var concept in concepts)
                        w.Line(
                            $"{qualifiedEnum}.{concept.ConstantName} => \"{EscapeString(concept.Code)}\","
                        );
                    w.Line(
                        "_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)"
                    );
                },
                trailingSemicolon: true
            );
            w.Line();

            // Display()
            w.Line(
                "/// <returns>The display label for this concept, or <c>null</c> if none.</returns>"
            );
            w.Line($"public static string? Display(this {qualifiedEnum} value) => value switch");
            w.Block(
                () =>
                {
                    foreach (var concept in concepts)
                    {
                        string displayLiteral = concept.Display is not null
                            ? $"\"{EscapeString(concept.Display)}\""
                            : "null";
                        w.Line($"{qualifiedEnum}.{concept.ConstantName} => {displayLiteral},");
                    }
                    w.Line(
                        "_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)"
                    );
                },
                trailingSemicolon: true
            );
            w.Line();

            // Coding()
            w.Line("/// <returns>A new <see cref=\"Coding\"/> for this concept.</returns>");
            w.Line($"public static Coding Coding(this {qualifiedEnum} value) =>");
            w.Indent(() => w.Line("new(value.Url(), value.Code(), value.Display());"));
            w.Line();

            // FromValue()
            w.Line("/// <param name=\"code\">The FHIR code to look up.</param>");
            w.Line(
                $"/// <returns>The matching <see cref=\"{qualifiedEnum}\"/>, or <c>null</c> if none matches.</returns>"
            );
            w.Line($"public static {qualifiedEnum}? FromValue(string code) => code switch");
            w.Block(
                () =>
                {
                    foreach (var concept in concepts)
                        w.Line(
                            $"\"{EscapeString(concept.Code)}\" => {qualifiedEnum}.{concept.ConstantName},"
                        );
                    w.Line("_ => null");
                },
                trailingSemicolon: true
            );
            w.Line();

            // FromValueOrThrow()
            w.Line("/// <param name=\"code\">The FHIR code to look up.</param>");
            w.Line($"/// <returns>The matching <see cref=\"{qualifiedEnum}\"/>.</returns>");
            w.Line(
                "/// <exception cref=\"ArgumentException\">If no constant has that code.</exception>"
            );
            w.Line($"public static {qualifiedEnum} FromValueOrThrow(string code) =>");
            w.Indent(() =>
                w.Line(
                    "FromValue(code) ?? throw new ArgumentException($\"Unknown code: {code}\", nameof(code));"
                )
            );
        });
    }

    // ── NamingSystems ────────────────────────────────────────────────────────

    private static void WriteNamingSystemsClass(CodeWriter w, IgPackageModel model)
    {
        if (model.NamingSystems.Count == 0)
            return;

        w.Line();
        w.Line("public static class NamingSystems");
        w.Block(() =>
        {
            bool firstNs = true;
            foreach (var (constantName, entry) in model.NamingSystems)
            {
                if (!firstNs)
                    w.Line();
                firstNs = false;

                string className = NameUtils.ToPascalCase(constantName);
                if (entry.Description is not null)
                    w.Line($"/// <summary>{XmlEscape(entry.Description)}</summary>");
                w.Line($"public static class {className}");
                w.Block(() =>
                {
                    w.Line("public static class UniqueId");
                    w.Block(() =>
                    {
                        bool firstType = true;
                        foreach (var (type, values) in entry.ByType)
                        {
                            if (!firstType)
                                w.Line();
                            firstType = false;

                            string propertyName = char.ToUpperInvariant(type[0]) + type[1..];
                            if (values.Count == 1)
                            {
                                w.Line($"/// <summary><c>{XmlEscape(values[0])}</c></summary>");
                                w.Line($"public static string {propertyName} =>");
                                w.Indent(() => w.Line($"\"{EscapeString(values[0])}\";"));
                            }
                            else
                            {
                                w.Line(
                                    $"/// <summary>All {XmlEscape(type)} unique identifiers.</summary>"
                                );
                                var literals = string.Join(
                                    ", ",
                                    values.Select(v => $"\"{EscapeString(v)}\"")
                                );
                                w.Line($"public static IReadOnlyList<string> {propertyName} =>");
                                w.Indent(() => w.Line($"[{literals}];"));
                            }
                        }
                    });
                });
            }
        });
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static IReadOnlyDictionary<string, string> BuildBoundEnumNames(IgPackageModel model)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var (constantName, _) in model.CodeSystemConcepts)
        {
            if (model.CodeSystems.TryGetValue(constantName, out var url))
                result[url] = NameUtils.ToPascalCase(constantName);
        }
        return result;
    }

    private static string FirelyTypeFor(string fhirTypeCode) =>
        FirelyTypeMap.TryGetValue(fhirTypeCode, out var mapped) ? mapped : fhirTypeCode;

    private static string XmlEscape(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string EscapeString(string text) =>
        text.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

/// <summary>Lightweight indentation-tracking string builder for code generation.</summary>
internal sealed class CodeWriter
{
    private readonly StringBuilder _sb = new();
    private int _indent;

    public void Line(string text = "")
    {
        if (text.Length == 0)
            _sb.AppendLine();
        else
            _sb.Append(' ', _indent * 4).AppendLine(text);
    }

    public void Indent(Action body)
    {
        _indent++;
        body();
        _indent--;
    }

    public void Block(Action body, bool trailingSemicolon = false)
    {
        Line("{");
        _indent++;
        body();
        _indent--;
        Line(trailingSemicolon ? "};" : "}");
    }

    public override string ToString() => _sb.ToString();
}
