<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ig-codegen</ToolCommandName>
    <PackageId>io.github.diz-uker.ig-codegen</PackageId>
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>
