// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.bildgebung 2026.0.0. Do
// not edit directly.
package de.medizininformatikinitiative.kerndatensatz.bildgebung;

import java.util.Optional;
import org.hl7.fhir.r4.model.Coding;
import org.hl7.fhir.r4.model.Extension;
import org.hl7.fhir.r4.model.IdType;
import org.hl7.fhir.r4.model.Quantity;
import org.hl7.fhir.r4.model.StringType;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

public final class Bildgebung {
  private Bildgebung() {}

  public static final class CodeSystems {
    private CodeSystems() {}

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type}
     */
    public static String miiCsBildgebungInstanceImageType() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence}
     */
    public static String miiCsBildgebungScanningSequence() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant}
     */
    public static String miiCsBildgebungScanningSequenceVariant() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type}
     */
    public static String miiCsBildgebungSeriesType() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type}
     */
    public static String miiCsBildgebungTransducerType() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type";
    }

    public enum MiiCsBildgebungInstanceImageType {
      /** {@code PDC} - Pixel Data Characteristics */
      PDC("PDC", "Pixel Data Characteristics"),

      /** {@code ORIGINAL} - identifies an original image */
      ORIGINAL("ORIGINAL", "identifies an original image"),

      /** {@code DERIVED} - identifies an derived image */
      DERIVED("DERIVED", "identifies an derived image"),

      /** {@code PEC} - Patient Examination Characteristics */
      PEC("PEC", "Patient Examination Characteristics"),

      /** {@code PRIMARY} - identifies a primary image */
      PRIMARY("PRIMARY", "identifies a primary image"),

      /** {@code SECONDARY} - identifies a secondary image */
      SECONDARY("SECONDARY", "identifies a secondary image"),

      /** {@code MSC} - Modality Specific Characteristics */
      MSC("MSC", "Modality Specific Characteristics"),

      /** {@code CT} - CT Specific Characteristics */
      CT("CT", "CT Specific Characteristics"),

      /** {@code AXIAL} - a CT Cross-sectional Image */
      AXIAL("AXIAL", "a CT Cross-sectional Image"),

      /** {@code LOCALIZER} - a CT Localizer Image */
      LOCALIZER("LOCALIZER", "a CT Localizer Image"),

      /** {@code MR} - MR Specific Characteristics */
      MR("MR", "MR Specific Characteristics"),

      /** {@code DENSITYMAP} - Density Map */
      DENSITYMAP("DENSITYMAP", "Density Map"),

      /** {@code DIFFUSIONMAP} - Diffusion Map */
      DIFFUSIONMAP("DIFFUSIONMAP", "Diffusion Map"),

      /** {@code IMAGEADDITION} - Image Addition */
      IMAGEADDITION("IMAGEADDITION", "Image Addition"),

      /** {@code MODULUSSUBTRACT} - Modulus Substract */
      MODULUSSUBTRACT("MODULUSSUBTRACT", "Modulus Substract"),

      /** {@code MPR} - MPR */
      MPR("MPR", "MPR"),

      /** {@code OTHER} - Other */
      OTHER("OTHER", "Other"),

      /** {@code PHASEMAP} - Phase Map */
      PHASEMAP("PHASEMAP", "Phase Map"),

      /** {@code PHASESUBTRACT} - Phase Substract */
      PHASESUBTRACT("PHASESUBTRACT", "Phase Substract"),

      /** {@code PROJECTIONIMAGE} - Projection Image */
      PROJECTIONIMAGE("PROJECTIONIMAGE", "Projection Image"),

      /** {@code T1MAP} - T1 Map */
      T1_MAP("T1MAP", "T1 Map"),

      /** {@code T2MAP} - T2 Map */
      T2_MAP("T2MAP", "T2 Map"),

      /** {@code VELOCITYMAP} - Velocity Map */
      VELOCITYMAP("VELOCITYMAP", "Velocity Map"),

      /** {@code NM} - NM Specific Characteristics */
      NM("NM", "NM Specific Characteristics"),

      /** {@code STATIC} - Static */
      STATIC("STATIC", "Static"),

      /** {@code DYNAMIC} - Dynamic */
      DYNAMIC("DYNAMIC", "Dynamic"),

      /** {@code GATED} - Gated */
      GATED("GATED", "Gated"),

      /** {@code WHOLEBODY} - Whole Body */
      WHOLEBODY("WHOLEBODY", "Whole Body"),

      /** {@code TOMO} - Tomo */
      TOMO("TOMO", "Tomo"),

      /** {@code GATEDTOMO} - Gated Tomo */
      GATEDTOMO("GATEDTOMO", "Gated Tomo"),

      /** {@code RECONTOMO} - Recon Tomo */
      RECONTOMO("RECONTOMO", "Recon Tomo"),

      /** {@code RECONGATEDTOMO} - Recon Gated Tomo */
      RECONGATEDTOMO("RECONGATEDTOMO", "Recon Gated Tomo"),

      /** {@code US} - US Specific Characteristics */
      US("US", "US Specific Characteristics"),

      /** {@code ABDOMINAL} - ABDOMINAL */
      ABDOMINAL("ABDOMINAL", "ABDOMINAL"),

      /** {@code BREAST} - BREAST */
      BREAST("BREAST", "BREAST"),

      /** {@code CHEST} - CHEST */
      CHEST("CHEST", "CHEST"),

      /** {@code ENDOCAVITARY} - ENDOCAVITARY */
      ENDOCAVITARY("ENDOCAVITARY", "ENDOCAVITARY"),

      /** {@code ENDORECTAL} - ENDORECTAL */
      ENDORECTAL("ENDORECTAL", "ENDORECTAL"),

      /** {@code ENDOVAGINAL} - ENDOVAGINAL */
      ENDOVAGINAL("ENDOVAGINAL", "ENDOVAGINAL"),

      /** {@code EPICARDIAL} - EPICARDIAL */
      EPICARDIAL("EPICARDIAL", "EPICARDIAL"),

      /** {@code FETAL_HEART} - FETAL HEART */
      FETAL_HEART("FETAL_HEART", "FETAL HEART"),

      /** {@code GYNECOLOGY} - GYNECOLOGY */
      GYNECOLOGY("GYNECOLOGY", "GYNECOLOGY"),

      /** {@code INTRACARDIAC} - INTRACARDIAC */
      INTRACARDIAC("INTRACARDIAC", "INTRACARDIAC"),

      /** {@code INTRAOPERATIVE} - INTRAOPERATIVE */
      INTRAOPERATIVE("INTRAOPERATIVE", "INTRAOPERATIVE"),

      /** {@code INTRAVASCULAR} - INTRAVASCULAR */
      INTRAVASCULAR("INTRAVASCULAR", "INTRAVASCULAR"),

      /** {@code MUSCULOSKELETAL} - MUSCULOSKELETAL */
      MUSCULOSKELETAL("MUSCULOSKELETAL", "MUSCULOSKELETAL"),

      /** {@code NEONATAL_HEAD} - NEONATAL HEAD */
      NEONATAL_HEAD("NEONATAL_HEAD", "NEONATAL HEAD"),

      /** {@code OBSTETRICAL} - OBSTETRICAL */
      OBSTETRICAL("OBSTETRICAL", "OBSTETRICAL"),

      /** {@code OPHTHALMIC} - OPHTHALMIC */
      OPHTHALMIC("OPHTHALMIC", "OPHTHALMIC"),

      /** {@code PEDIATRIC} - PEDIATRIC */
      PEDIATRIC("PEDIATRIC", "PEDIATRIC"),

      /** {@code PELVIC} - PELVIC */
      PELVIC("PELVIC", "PELVIC"),

      /** {@code RETROPERITONEAL} - RETROPERITONEAL */
      RETROPERITONEAL("RETROPERITONEAL", "RETROPERITONEAL"),

      /** {@code SCROTAL} - SCROTAL */
      SCROTAL("SCROTAL", "SCROTAL"),

      /** {@code SMALL_PARTS} - SMALL PARTS */
      SMALL_PARTS("SMALL_PARTS", "SMALL PARTS"),

      /** {@code TEE} - TEE */
      TEE("TEE", "TEE"),

      /** {@code THYROID} - THYROID */
      THYROID("THYROID", "THYROID"),

      /** {@code TRANSCRANIAL} - TRANSCRANIAL */
      TRANSCRANIAL("TRANSCRANIAL", "TRANSCRANIAL"),

      /** {@code TTE} - TTE */
      TTE("TTE", "TTE"),

      /** {@code US_BIOPSY} - US BIOPSY */
      US_BIOPSY("US_BIOPSY", "US BIOPSY"),

      /** {@code VASCULAR} - VASCULAR */
      VASCULAR("VASCULAR", "VASCULAR"),

      /** {@code ISI} - Implemetation Specific Identifiers */
      ISI("ISI", "Implemetation Specific Identifiers"),

      /** {@code NMI} - NM Implematation */
      NMI("NMI", "NM Implematation"),

      /** {@code EMISSION} - Emission */
      EMISSION("EMISSION", "Emission"),

      /** {@code TRANSMISSION} - Transmission */
      TRANSMISSION("TRANSMISSION", "Transmission"),

      /** {@code USI} - US Implemantation */
      USI("USI", "US Implemantation"),

      /** {@code 0001} - 2D Imaging */
      _0001("0001", "2D Imaging"),

      /** {@code 0002} - M-Mode */
      _0002("0002", "M-Mode"),

      /** {@code 0004} - CW Doppler */
      _0004("0004", "CW Doppler"),

      /** {@code 0008} - PW Doppler */
      _0008("0008", "PW Doppler"),

      /** {@code 0010} - Color Doppler */
      _0010("0010", "Color Doppler"),

      /** {@code 0020} - Color M-Mode */
      _0020("0020", "Color M-Mode"),

      /** {@code 0040} - 3D Rendering */
      _0040("0040", "3D Rendering"),

      /** {@code 0100} - Color Power Mode */
      _0100("0100", "Color Power Mode"),

      /** {@code 0200} - Tissue Characterization */
      _0200("0200", "Tissue Characterization"),

      /** {@code 0400} - Spatially-related frames */
      _0400("0400", "Spatially-related frames");

      private final @NonNull String code;

      private final @Nullable String display;

      MiiCsBildgebungInstanceImageType(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type}
       */
      public @NonNull Coding coding(@NonNull MiiCsBildgebungInstanceImageType this) {
        return new Coding(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type",
            code,
            display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if
       *     none matches
       */
      public static Optional<@NonNull MiiCsBildgebungInstanceImageType> fromValue(
          @NonNull String code) {
        for (MiiCsBildgebungInstanceImageType value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} matches
       * @throws IllegalArgumentException if no constant has that code
       */
      public static @NonNull MiiCsBildgebungInstanceImageType fromValueOrThrow(
          @NonNull String code) {
        return fromValue(code)
            .orElseThrow(() -> new IllegalArgumentException("Unknown code: " + code));
      }
    }

    public enum MiiCsBildgebungScanningSequence {
      /** {@code SE} - Spin Echo */
      SE("SE", "Spin Echo"),

      /** {@code IR} - Inversion Recovery */
      IR("IR", "Inversion Recovery"),

      /** {@code GR} - Gradient Recalled */
      GR("GR", "Gradient Recalled"),

      /** {@code EP} - Echo Planar */
      EP("EP", "Echo Planar"),

      /** {@code RM} - Research Mode */
      RM("RM", "Research Mode");

      private final @NonNull String code;

      private final @Nullable String display;

      MiiCsBildgebungScanningSequence(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence}
       */
      public @NonNull Coding coding(@NonNull MiiCsBildgebungScanningSequence this) {
        return new Coding(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence",
            code,
            display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if
       *     none matches
       */
      public static Optional<@NonNull MiiCsBildgebungScanningSequence> fromValue(
          @NonNull String code) {
        for (MiiCsBildgebungScanningSequence value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} matches
       * @throws IllegalArgumentException if no constant has that code
       */
      public static @NonNull MiiCsBildgebungScanningSequence fromValueOrThrow(
          @NonNull String code) {
        return fromValue(code)
            .orElseThrow(() -> new IllegalArgumentException("Unknown code: " + code));
      }
    }

    public enum MiiCsBildgebungScanningSequenceVariant {
      /** {@code SK} - segmented k-space */
      SK("SK", "segmented k-space"),

      /** {@code MTC} - magnetization transfer contrast */
      MTC("MTC", "magnetization transfer contrast"),

      /** {@code SS} - steady state */
      SS("SS", "steady state"),

      /** {@code TRSS} - time reversed steady state */
      TRSS("TRSS", "time reversed steady state"),

      /** {@code SP} - spoiled */
      SP("SP", "spoiled"),

      /** {@code MP} - MAG prepared */
      MP("MP", "MAG prepared"),

      /** {@code OSP} - oversampling phase */
      OSP("OSP", "oversampling phase"),

      /** {@code NONE} - no sequence variant */
      NONE("NONE", "no sequence variant");

      private final @NonNull String code;

      private final @Nullable String display;

      MiiCsBildgebungScanningSequenceVariant(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant}
       */
      public @NonNull Coding coding(@NonNull MiiCsBildgebungScanningSequenceVariant this) {
        return new Coding(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant",
            code,
            display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if
       *     none matches
       */
      public static Optional<@NonNull MiiCsBildgebungScanningSequenceVariant> fromValue(
          @NonNull String code) {
        for (MiiCsBildgebungScanningSequenceVariant value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} matches
       * @throws IllegalArgumentException if no constant has that code
       */
      public static @NonNull MiiCsBildgebungScanningSequenceVariant fromValueOrThrow(
          @NonNull String code) {
        return fromValue(code)
            .orElseThrow(() -> new IllegalArgumentException("Unknown code: " + code));
      }
    }

    public enum MiiCsBildgebungSeriesType {
      /** {@code STATIC} - a group of images at varying spatial locations at the same time */
      STATIC("STATIC", "a group of images at varying spatial locations at the same time"),

      /**
       * {@code DYNAMIC} - a group of images at a set of spatial locations (e.g., slices) at varying
       * time slices, with all spatial locations acquired at all time slices
       */
      DYNAMIC(
          "DYNAMIC",
          "a group of images at a set of spatial locations (e.g., slices) at varying time slices, with all spatial locations acquired at all time slices"),

      /**
       * {@code GATED} - a group of images at the same spatial location, same starting and ending
       * time, but acquired in different time slots of (possibly) different R-R intervals
       */
      GATED(
          "GATED",
          "a group of images at the same spatial location, same starting and ending time, but acquired in different time slots of (possibly) different R-R intervals"),

      /**
       * {@code WHOLEBODY} - same as STATIC, except covering multiple transverse fields of view (and
       * therefore acquired at a different time)
       */
      WHOLEBODY(
          "WHOLEBODY",
          "same as STATIC, except covering multiple transverse fields of view (and therefore acquired at a different time)"),

      /** {@code IMAGE} - a tomographic image slice */
      IMAGE("IMAGE", "a tomographic image slice"),

      /**
       * {@code REPROJECTION} - a projection image derived from forward projection through slices of
       * tomographic images, using the algorithm defined in Reprojection Method (0054,1004)
       */
      REPROJECTION(
          "REPROJECTION",
          "a projection image derived from forward projection through slices of tomographic images, using the algorithm defined in Reprojection Method (0054,1004)");

      private final @NonNull String code;

      private final @Nullable String display;

      MiiCsBildgebungSeriesType(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type}
       */
      public @NonNull Coding coding(@NonNull MiiCsBildgebungSeriesType this) {
        return new Coding(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type",
            code,
            display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if
       *     none matches
       */
      public static Optional<@NonNull MiiCsBildgebungSeriesType> fromValue(@NonNull String code) {
        for (MiiCsBildgebungSeriesType value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} matches
       * @throws IllegalArgumentException if no constant has that code
       */
      public static @NonNull MiiCsBildgebungSeriesType fromValueOrThrow(@NonNull String code) {
        return fromValue(code)
            .orElseThrow(() -> new IllegalArgumentException("Unknown code: " + code));
      }
    }

    public enum MiiCsBildgebungTransducerType {
      /** {@code SECTOR_PHASED} - Sector Phased */
      SECTOR_PHASED("SECTOR_PHASED", "Sector Phased"),

      /** {@code SECTOR_MECH} - Sector Mech */
      SECTOR_MECH("SECTOR_MECH", "Sector Mech"),

      /** {@code SECTOR_ANNULAR} - Sector Annular */
      SECTOR_ANNULAR("SECTOR_ANNULAR", "Sector Annular"),

      /** {@code LINEAR} - Linear */
      LINEAR("LINEAR", "Linear"),

      /** {@code CURVED_LINEAR} - Curved Linear */
      CURVED_LINEAR("CURVED_LINEAR", "Curved Linear"),

      /** {@code SINGLE_CRYSTAL} - Single Crystal */
      SINGLE_CRYSTAL("SINGLE_CRYSTAL", "Single Crystal"),

      /** {@code SPLIT_XTAL_CWD} - Split Xtal CWD */
      SPLIT_XTAL_CWD("SPLIT_XTAL_CWD", "Split Xtal CWD"),

      /** {@code IV_PHASED} - IV Phased */
      IV_PHASED("IV_PHASED", "IV Phased"),

      /** {@code IV_ROT_XTAL} - IV Rot XTAL */
      IV_ROT_XTAL("IV_ROT_XTAL", "IV Rot XTAL"),

      /** {@code IV_ROT_MIRROR} - IV Rot Mirror */
      IV_ROT_MIRROR("IV_ROT_MIRROR", "IV Rot Mirror"),

      /** {@code ENDOCAV_PA} - Endocav PA */
      ENDOCAV_PA("ENDOCAV_PA", "Endocav PA"),

      /** {@code ENDOCAV_MECH} - Endocav Mech */
      ENDOCAV_MECH("ENDOCAV_MECH", "Endocav Mech"),

      /** {@code ENDOCAV_CLA} - EndocavCLA */
      ENDOCAV_CLA("ENDOCAV_CLA", "EndocavCLA"),

      /** {@code ENDOCAV_AA} - Endocav AA */
      ENDOCAV_AA("ENDOCAV_AA", "Endocav AA"),

      /** {@code ENDOCAV_LINEAR} - Endocav Linear */
      ENDOCAV_LINEAR("ENDOCAV_LINEAR", "Endocav Linear"),

      /** {@code VECTOR_PHASED} - Vector Phased */
      VECTOR_PHASED("VECTOR_PHASED", "Vector Phased");

      private final @NonNull String code;

      private final @Nullable String display;

      MiiCsBildgebungTransducerType(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type}
       */
      public @NonNull Coding coding(@NonNull MiiCsBildgebungTransducerType this) {
        return new Coding(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type",
            code,
            display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if
       *     none matches
       */
      public static Optional<@NonNull MiiCsBildgebungTransducerType> fromValue(
          @NonNull String code) {
        for (MiiCsBildgebungTransducerType value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} matches
       * @throws IllegalArgumentException if no constant has that code
       */
      public static @NonNull MiiCsBildgebungTransducerType fromValueOrThrow(@NonNull String code) {
        return fromValue(code)
            .orElseThrow(() -> new IllegalArgumentException("Unknown code: " + code));
      }
    }
  }

  public static final class Profiles {
    private Profiles() {}

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-anforderung-bildgebung|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-anforderung-bildgebung|2026.0.0}
     */
    public static String miiPrBildgebungAnforderungBildgebung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-anforderung-bildgebung|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-behandlungsempfehlung|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-behandlungsempfehlung|2026.0.0}
     */
    public static String miiPrBildgebungBehandlungsempfehlung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-behandlungsempfehlung|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsprozedur|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsprozedur|2026.0.0}
     */
    public static String miiPrBildgebungBildgebungsprozedur() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsprozedur|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsstudie|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsstudie|2026.0.0}
     */
    public static String miiPrBildgebungBildgebungsstudie() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsstudie|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-geraet|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-geraet|2026.0.0}
     */
    public static String miiPrBildgebungGeraet() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-geraet|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-koerperstruktur|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-koerperstruktur|2026.0.0}
     */
    public static String miiPrBildgebungKoerperstruktur() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-koerperstruktur|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-kontrastmittelgabe|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-kontrastmittelgabe|2026.0.0}
     */
    public static String miiPrBildgebungKontrastmittelgabe() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-kontrastmittelgabe|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologischer-befund|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologischer-befund|2026.0.0}
     */
    public static String miiPrBildgebungRadiologischerBefund() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologischer-befund|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-befundungsprozedur|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-befundungsprozedur|2026.0.0}
     */
    public static String miiPrBildgebungRadiologischeBefundungsprozedur() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-befundungsprozedur|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-beobachtung|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-beobachtung|2026.0.0}
     */
    public static String miiPrBildgebungRadiologischeBeobachtung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-beobachtung|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-semistrukt-befundbericht|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-semistrukt-befundbericht|2026.0.0}
     */
    public static String miiPrBildgebungSemistruktBefundbericht() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-semistrukt-befundbericht|2026.0.0";
    }
  }

  public static final class Extensions {
    private Extensions() {}

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund}
     *     and the given value
     */
    public static @NonNull Extension miiExBildgebungBildgebungsgrund(@NonNull StringType value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund",
          value);
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungInstanzDetails() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details");
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungKontrastmittel() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel");
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungModalitaetCt() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct");
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungModalitaetMgCrDx() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx");
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungModalitaetMr() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr");
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungModalitaetNm() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm");
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungModalitaetPt() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt");
    }

    /**
     * A new, empty {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us},
     * for further population with nested extensions via {@link Extension#addExtension}.
     *
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us}
     *     and no value
     */
    public static @NonNull Extension miiExBildgebungModalitaetUs() {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us");
    }

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke}
     *     and the given value
     */
    public static @NonNull Extension miiExBildgebungSerieSchichtdicke(@NonNull Quantity value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke",
          value);
    }

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid}
     *     and the given value
     */
    public static @NonNull Extension miiExBildgebungSerieUid(@NonNull IdType value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid",
          value);
    }

    /**
     * A new {@link Extension} for the canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid}
     *     and the given value
     */
    public static @NonNull Extension miiExBildgebungSopInstanzUid(@NonNull IdType value) {
      return new Extension(
          "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid",
          value);
    }
  }
}
