"""Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.medikation 2026.0.1. Do not edit directly."""

from enum import Enum
from typing import Self

from fhir.resources.R4B.coding import Coding


class Medikation:
    class CodeSystems:
        @staticmethod
        def mii_cs_medikation_wirkstofftyp() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp"

        class MiiCsMedikationWirkstofftyp(Enum):
            IN = ("IN", "ingredient")
            PIN = ("PIN", "precise ingredient")
            MIN = ("MIN", "multiple ingredients")

            def __init__(self, code: str, display: str | None) -> None:
                self.code = code
                self.display = display

            def coding(self) -> Coding:
                """Returns a new `Coding` for this concept, with system ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp``."""
                return Coding(
                    system="https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp",
                    code=self.code,
                    display=self.display,
                )

            @classmethod
            def from_value(cls, code: str) -> Self:
                """Looks up the member whose ``code`` equals ``code``.

                Raises:
                    ValueError: if no member has that code.
                """
                for member in cls:
                    if member.code == code:
                        return member
                raise ValueError(f"Unknown code: {code}")

    class Profiles:
        @staticmethod
        def mii_pr_medikation_medication() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1"

        @staticmethod
        def mii_pr_medikation_medication_administration() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1"

        @staticmethod
        def mii_pr_medikation_medication_request() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1"

        @staticmethod
        def mii_pr_medikation_medication_statement() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1"

        @staticmethod
        def mii_pr_medikation_medikationsliste() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1"

    class Extensions:
        @staticmethod
        def mii_ex_medikation_wirkstoffrelation() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation"

        @staticmethod
        def mii_ex_medikation_wirkstofftyp() -> str:
            """The canonical URL ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp``.

            Returns:
                ``https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp``
            """
            return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp"
