// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.bildgebung 2026.0.0. Do not edit directly.
using Hl7.Fhir.Model;

namespace De.Medizininformatikinitiative.Kerndatensatz.Bildgebung;

public static class Bildgebung
{
    public static class CodeSystems
    {
        public static class Urls
        {
            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type</c>.</summary>
            public static string MiiCsBildgebungInstanceImageType =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type";

            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence</c>.</summary>
            public static string MiiCsBildgebungScanningSequence =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence";

            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant</c>.</summary>
            public static string MiiCsBildgebungScanningSequenceVariant =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant";

            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type</c>.</summary>
            public static string MiiCsBildgebungSeriesType =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type";

            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type</c>.</summary>
            public static string MiiCsBildgebungTransducerType =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type";
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type</c>.</summary>
        public enum MiiCsBildgebungInstanceImageType
        {
            /// <summary><c>PDC</c> - Pixel Data Characteristics</summary>
            Pdc,

            /// <summary><c>ORIGINAL</c> - identifies an original image</summary>
            Original,

            /// <summary><c>DERIVED</c> - identifies an derived image</summary>
            Derived,

            /// <summary><c>PEC</c> - Patient Examination Characteristics</summary>
            Pec,

            /// <summary><c>PRIMARY</c> - identifies a primary image</summary>
            Primary,

            /// <summary><c>SECONDARY</c> - identifies a secondary image</summary>
            Secondary,

            /// <summary><c>MSC</c> - Modality Specific Characteristics</summary>
            Msc,

            /// <summary><c>CT</c> - CT Specific Characteristics</summary>
            Ct,

            /// <summary><c>AXIAL</c> - a CT Cross-sectional Image</summary>
            Axial,

            /// <summary><c>LOCALIZER</c> - a CT Localizer Image</summary>
            Localizer,

            /// <summary><c>MR</c> - MR Specific Characteristics</summary>
            Mr,

            /// <summary><c>DENSITYMAP</c> - Density Map</summary>
            Densitymap,

            /// <summary><c>DIFFUSIONMAP</c> - Diffusion Map</summary>
            Diffusionmap,

            /// <summary><c>IMAGEADDITION</c> - Image Addition</summary>
            Imageaddition,

            /// <summary><c>MODULUSSUBTRACT</c> - Modulus Substract</summary>
            Modulussubtract,

            /// <summary><c>MPR</c> - MPR</summary>
            Mpr,

            /// <summary><c>OTHER</c> - Other</summary>
            Other,

            /// <summary><c>PHASEMAP</c> - Phase Map</summary>
            Phasemap,

            /// <summary><c>PHASESUBTRACT</c> - Phase Substract</summary>
            Phasesubtract,

            /// <summary><c>PROJECTIONIMAGE</c> - Projection Image</summary>
            Projectionimage,

            /// <summary><c>T1MAP</c> - T1 Map</summary>
            T1Map,

            /// <summary><c>T2MAP</c> - T2 Map</summary>
            T2Map,

            /// <summary><c>VELOCITYMAP</c> - Velocity Map</summary>
            Velocitymap,

            /// <summary><c>NM</c> - NM Specific Characteristics</summary>
            Nm,

            /// <summary><c>STATIC</c> - Static</summary>
            Static,

            /// <summary><c>DYNAMIC</c> - Dynamic</summary>
            Dynamic,

            /// <summary><c>GATED</c> - Gated</summary>
            Gated,

            /// <summary><c>WHOLEBODY</c> - Whole Body</summary>
            Wholebody,

            /// <summary><c>TOMO</c> - Tomo</summary>
            Tomo,

            /// <summary><c>GATEDTOMO</c> - Gated Tomo</summary>
            Gatedtomo,

            /// <summary><c>RECONTOMO</c> - Recon Tomo</summary>
            Recontomo,

            /// <summary><c>RECONGATEDTOMO</c> - Recon Gated Tomo</summary>
            Recongatedtomo,

            /// <summary><c>US</c> - US Specific Characteristics</summary>
            Us,

            /// <summary><c>ABDOMINAL</c> - ABDOMINAL</summary>
            Abdominal,

            /// <summary><c>BREAST</c> - BREAST</summary>
            Breast,

            /// <summary><c>CHEST</c> - CHEST</summary>
            Chest,

            /// <summary><c>ENDOCAVITARY</c> - ENDOCAVITARY</summary>
            Endocavitary,

            /// <summary><c>ENDORECTAL</c> - ENDORECTAL</summary>
            Endorectal,

            /// <summary><c>ENDOVAGINAL</c> - ENDOVAGINAL</summary>
            Endovaginal,

            /// <summary><c>EPICARDIAL</c> - EPICARDIAL</summary>
            Epicardial,

            /// <summary><c>FETAL_HEART</c> - FETAL HEART</summary>
            FetalHeart,

            /// <summary><c>GYNECOLOGY</c> - GYNECOLOGY</summary>
            Gynecology,

            /// <summary><c>INTRACARDIAC</c> - INTRACARDIAC</summary>
            Intracardiac,

            /// <summary><c>INTRAOPERATIVE</c> - INTRAOPERATIVE</summary>
            Intraoperative,

            /// <summary><c>INTRAVASCULAR</c> - INTRAVASCULAR</summary>
            Intravascular,

            /// <summary><c>MUSCULOSKELETAL</c> - MUSCULOSKELETAL</summary>
            Musculoskeletal,

            /// <summary><c>NEONATAL_HEAD</c> - NEONATAL HEAD</summary>
            NeonatalHead,

            /// <summary><c>OBSTETRICAL</c> - OBSTETRICAL</summary>
            Obstetrical,

            /// <summary><c>OPHTHALMIC</c> - OPHTHALMIC</summary>
            Ophthalmic,

            /// <summary><c>PEDIATRIC</c> - PEDIATRIC</summary>
            Pediatric,

            /// <summary><c>PELVIC</c> - PELVIC</summary>
            Pelvic,

            /// <summary><c>RETROPERITONEAL</c> - RETROPERITONEAL</summary>
            Retroperitoneal,

            /// <summary><c>SCROTAL</c> - SCROTAL</summary>
            Scrotal,

            /// <summary><c>SMALL_PARTS</c> - SMALL PARTS</summary>
            SmallParts,

            /// <summary><c>TEE</c> - TEE</summary>
            Tee,

            /// <summary><c>THYROID</c> - THYROID</summary>
            Thyroid,

            /// <summary><c>TRANSCRANIAL</c> - TRANSCRANIAL</summary>
            Transcranial,

            /// <summary><c>TTE</c> - TTE</summary>
            Tte,

            /// <summary><c>US_BIOPSY</c> - US BIOPSY</summary>
            UsBiopsy,

            /// <summary><c>VASCULAR</c> - VASCULAR</summary>
            Vascular,

            /// <summary><c>ISI</c> - Implemetation Specific Identifiers</summary>
            Isi,

            /// <summary><c>NMI</c> - NM Implematation</summary>
            Nmi,

            /// <summary><c>EMISSION</c> - Emission</summary>
            Emission,

            /// <summary><c>TRANSMISSION</c> - Transmission</summary>
            Transmission,

            /// <summary><c>USI</c> - US Implemantation</summary>
            Usi,

            /// <summary><c>0001</c> - 2D Imaging</summary>
            _0001,

            /// <summary><c>0002</c> - M-Mode</summary>
            _0002,

            /// <summary><c>0004</c> - CW Doppler</summary>
            _0004,

            /// <summary><c>0008</c> - PW Doppler</summary>
            _0008,

            /// <summary><c>0010</c> - Color Doppler</summary>
            _0010,

            /// <summary><c>0020</c> - Color M-Mode</summary>
            _0020,

            /// <summary><c>0040</c> - 3D Rendering</summary>
            _0040,

            /// <summary><c>0100</c> - Color Power Mode</summary>
            _0100,

            /// <summary><c>0200</c> - Tissue Characterization</summary>
            _0200,

            /// <summary><c>0400</c> - Spatially-related frames</summary>
            _0400,
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence</c>.</summary>
        public enum MiiCsBildgebungScanningSequence
        {
            /// <summary><c>SE</c> - Spin Echo</summary>
            Se,

            /// <summary><c>IR</c> - Inversion Recovery</summary>
            Ir,

            /// <summary><c>GR</c> - Gradient Recalled</summary>
            Gr,

            /// <summary><c>EP</c> - Echo Planar</summary>
            Ep,

            /// <summary><c>RM</c> - Research Mode</summary>
            Rm,
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant</c>.</summary>
        public enum MiiCsBildgebungScanningSequenceVariant
        {
            /// <summary><c>SK</c> - segmented k-space</summary>
            Sk,

            /// <summary><c>MTC</c> - magnetization transfer contrast</summary>
            Mtc,

            /// <summary><c>SS</c> - steady state</summary>
            Ss,

            /// <summary><c>TRSS</c> - time reversed steady state</summary>
            Trss,

            /// <summary><c>SP</c> - spoiled</summary>
            Sp,

            /// <summary><c>MP</c> - MAG prepared</summary>
            Mp,

            /// <summary><c>OSP</c> - oversampling phase</summary>
            Osp,

            /// <summary><c>NONE</c> - no sequence variant</summary>
            None,
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type</c>.</summary>
        public enum MiiCsBildgebungSeriesType
        {
            /// <summary><c>STATIC</c> - a group of images at varying spatial locations at the same time</summary>
            Static,

            /// <summary><c>DYNAMIC</c> - a group of images at a set of spatial locations (e.g., slices) at varying time slices, with all spatial locations acquired at all time slices</summary>
            Dynamic,

            /// <summary><c>GATED</c> - a group of images at the same spatial location, same starting and ending time, but acquired in different time slots of (possibly) different R-R intervals</summary>
            Gated,

            /// <summary><c>WHOLEBODY</c> - same as STATIC, except covering multiple transverse fields of view (and therefore acquired at a different time)</summary>
            Wholebody,

            /// <summary><c>IMAGE</c> - a tomographic image slice</summary>
            Image,

            /// <summary><c>REPROJECTION</c> - a projection image derived from forward projection through slices of tomographic images, using the algorithm defined in Reprojection Method (0054,1004)</summary>
            Reprojection,
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type</c>.</summary>
        public enum MiiCsBildgebungTransducerType
        {
            /// <summary><c>SECTOR_PHASED</c> - Sector Phased</summary>
            SectorPhased,

            /// <summary><c>SECTOR_MECH</c> - Sector Mech</summary>
            SectorMech,

            /// <summary><c>SECTOR_ANNULAR</c> - Sector Annular</summary>
            SectorAnnular,

            /// <summary><c>LINEAR</c> - Linear</summary>
            Linear,

            /// <summary><c>CURVED_LINEAR</c> - Curved Linear</summary>
            CurvedLinear,

            /// <summary><c>SINGLE_CRYSTAL</c> - Single Crystal</summary>
            SingleCrystal,

            /// <summary><c>SPLIT_XTAL_CWD</c> - Split Xtal CWD</summary>
            SplitXtalCwd,

            /// <summary><c>IV_PHASED</c> - IV Phased</summary>
            IvPhased,

            /// <summary><c>IV_ROT_XTAL</c> - IV Rot XTAL</summary>
            IvRotXtal,

            /// <summary><c>IV_ROT_MIRROR</c> - IV Rot Mirror</summary>
            IvRotMirror,

            /// <summary><c>ENDOCAV_PA</c> - Endocav PA</summary>
            EndocavPa,

            /// <summary><c>ENDOCAV_MECH</c> - Endocav Mech</summary>
            EndocavMech,

            /// <summary><c>ENDOCAV_CLA</c> - EndocavCLA</summary>
            EndocavCla,

            /// <summary><c>ENDOCAV_AA</c> - Endocav AA</summary>
            EndocavAa,

            /// <summary><c>ENDOCAV_LINEAR</c> - Endocav Linear</summary>
            EndocavLinear,

            /// <summary><c>VECTOR_PHASED</c> - Vector Phased</summary>
            VectorPhased,
        }
    }

    public static class Profiles
    {
        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-anforderung-bildgebung|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungAnforderungBildgebung =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-anforderung-bildgebung|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-behandlungsempfehlung|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungBehandlungsempfehlung =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-behandlungsempfehlung|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsprozedur|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungBildgebungsprozedur =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsprozedur|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsstudie|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungBildgebungsstudie =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-bildgebungsstudie|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-geraet|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungGeraet =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-geraet|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-koerperstruktur|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungKoerperstruktur =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-koerperstruktur|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-kontrastmittelgabe|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungKontrastmittelgabe =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-kontrastmittelgabe|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologischer-befund|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungRadiologischerBefund =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologischer-befund|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-befundungsprozedur|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungRadiologischeBefundungsprozedur =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-befundungsprozedur|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-beobachtung|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungRadiologischeBeobachtung =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-radiologische-beobachtung|2026.0.0";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-semistrukt-befundbericht|2026.0.0</c>.</summary>
        public static string MiiPrBildgebungSemistruktBefundbericht =>
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-pr-bildgebung-semistrukt-befundbericht|2026.0.0";
    }

    public static class Extensions
    {
        public static class Urls
        {
            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund</c>.</summary>
            public static string MiiExBildgebungBildgebungsgrund =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details</c>.</summary>
            public static string MiiExBildgebungInstanzDetails =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel</c>.</summary>
            public static string MiiExBildgebungKontrastmittel =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct</c>.</summary>
            public static string MiiExBildgebungModalitaetCt =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx</c>.</summary>
            public static string MiiExBildgebungModalitaetMgCrDx =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr</c>.</summary>
            public static string MiiExBildgebungModalitaetMr =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm</c>.</summary>
            public static string MiiExBildgebungModalitaetNm =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt</c>.</summary>
            public static string MiiExBildgebungModalitaetPt =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us</c>.</summary>
            public static string MiiExBildgebungModalitaetUs =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke</c>.</summary>
            public static string MiiExBildgebungSerieSchichtdicke =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid</c>.</summary>
            public static string MiiExBildgebungSerieUid =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid</c>.</summary>
            public static string MiiExBildgebungSopInstanzUid =>
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid";
        }

        /// <summary>A new <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund</c> and the given value.</returns>
        public static Extension MiiExBildgebungBildgebungsgrund(FhirString value) =>
            new(
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund",
                value
            );

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details</c> and no value.</returns>
        public static Extension MiiExBildgebungInstanzDetails() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details",
            };

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel</c> and no value.</returns>
        public static Extension MiiExBildgebungKontrastmittel() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel",
            };

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct</c> and no value.</returns>
        public static Extension MiiExBildgebungModalitaetCt() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct",
            };

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx</c> and no value.</returns>
        public static Extension MiiExBildgebungModalitaetMgCrDx() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx",
            };

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr</c> and no value.</returns>
        public static Extension MiiExBildgebungModalitaetMr() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr",
            };

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm</c> and no value.</returns>
        public static Extension MiiExBildgebungModalitaetNm() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm",
            };

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt</c> and no value.</returns>
        public static Extension MiiExBildgebungModalitaetPt() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt",
            };

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us</c> and no value.</returns>
        public static Extension MiiExBildgebungModalitaetUs() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us",
            };

        /// <summary>A new <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke</c> and the given value.</returns>
        public static Extension MiiExBildgebungSerieSchichtdicke(Quantity value) =>
            new(
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke",
                value
            );

        /// <summary>A new <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid</c> and the given value.</returns>
        public static Extension MiiExBildgebungSerieUid(Id value) =>
            new(
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid",
                value
            );

        /// <summary>A new <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid</c> and the given value.</returns>
        public static Extension MiiExBildgebungSopInstanzUid(Id value) =>
            new(
                "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid",
                value
            );
    }
}

/// <summary>Extension methods for <see cref="Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType"/>.</summary>
public static class MiiCsBildgebungInstanceImageTypeExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type</c>.</returns>
    public static string Url(this Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType _) =>
        "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-instance-image-type";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType value) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pdc => "PDC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Original => "ORIGINAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Derived => "DERIVED",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pec => "PEC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Primary => "PRIMARY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Secondary => "SECONDARY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Msc => "MSC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Ct => "CT",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Axial => "AXIAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Localizer => "LOCALIZER",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Mr => "MR",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Densitymap => "DENSITYMAP",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Diffusionmap => "DIFFUSIONMAP",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Imageaddition =>
                "IMAGEADDITION",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Modulussubtract =>
                "MODULUSSUBTRACT",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Mpr => "MPR",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Other => "OTHER",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Phasemap => "PHASEMAP",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Phasesubtract =>
                "PHASESUBTRACT",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Projectionimage =>
                "PROJECTIONIMAGE",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.T1Map => "T1MAP",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.T2Map => "T2MAP",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Velocitymap => "VELOCITYMAP",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Nm => "NM",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Static => "STATIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Dynamic => "DYNAMIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gated => "GATED",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Wholebody => "WHOLEBODY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tomo => "TOMO",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gatedtomo => "GATEDTOMO",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Recontomo => "RECONTOMO",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Recongatedtomo =>
                "RECONGATEDTOMO",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Us => "US",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Abdominal => "ABDOMINAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Breast => "BREAST",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Chest => "CHEST",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endocavitary => "ENDOCAVITARY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endorectal => "ENDORECTAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endovaginal => "ENDOVAGINAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Epicardial => "EPICARDIAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.FetalHeart => "FETAL_HEART",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gynecology => "GYNECOLOGY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Intracardiac => "INTRACARDIAC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Intraoperative =>
                "INTRAOPERATIVE",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Intravascular =>
                "INTRAVASCULAR",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Musculoskeletal =>
                "MUSCULOSKELETAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.NeonatalHead => "NEONATAL_HEAD",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Obstetrical => "OBSTETRICAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Ophthalmic => "OPHTHALMIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pediatric => "PEDIATRIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pelvic => "PELVIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Retroperitoneal =>
                "RETROPERITONEAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Scrotal => "SCROTAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.SmallParts => "SMALL_PARTS",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tee => "TEE",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Thyroid => "THYROID",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Transcranial => "TRANSCRANIAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tte => "TTE",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.UsBiopsy => "US_BIOPSY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Vascular => "VASCULAR",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Isi => "ISI",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Nmi => "NMI",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Emission => "EMISSION",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Transmission => "TRANSMISSION",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Usi => "USI",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0001 => "0001",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0002 => "0002",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0004 => "0004",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0008 => "0008",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0010 => "0010",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0020 => "0020",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0040 => "0040",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0100 => "0100",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0200 => "0200",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0400 => "0400",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(
        this Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType value
    ) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pdc =>
                "Pixel Data Characteristics",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Original =>
                "identifies an original image",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Derived =>
                "identifies an derived image",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pec =>
                "Patient Examination Characteristics",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Primary =>
                "identifies a primary image",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Secondary =>
                "identifies a secondary image",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Msc =>
                "Modality Specific Characteristics",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Ct =>
                "CT Specific Characteristics",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Axial =>
                "a CT Cross-sectional Image",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Localizer =>
                "a CT Localizer Image",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Mr =>
                "MR Specific Characteristics",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Densitymap => "Density Map",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Diffusionmap => "Diffusion Map",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Imageaddition =>
                "Image Addition",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Modulussubtract =>
                "Modulus Substract",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Mpr => "MPR",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Other => "Other",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Phasemap => "Phase Map",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Phasesubtract =>
                "Phase Substract",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Projectionimage =>
                "Projection Image",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.T1Map => "T1 Map",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.T2Map => "T2 Map",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Velocitymap => "Velocity Map",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Nm =>
                "NM Specific Characteristics",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Static => "Static",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Dynamic => "Dynamic",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gated => "Gated",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Wholebody => "Whole Body",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tomo => "Tomo",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gatedtomo => "Gated Tomo",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Recontomo => "Recon Tomo",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Recongatedtomo =>
                "Recon Gated Tomo",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Us =>
                "US Specific Characteristics",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Abdominal => "ABDOMINAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Breast => "BREAST",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Chest => "CHEST",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endocavitary => "ENDOCAVITARY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endorectal => "ENDORECTAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endovaginal => "ENDOVAGINAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Epicardial => "EPICARDIAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.FetalHeart => "FETAL HEART",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gynecology => "GYNECOLOGY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Intracardiac => "INTRACARDIAC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Intraoperative =>
                "INTRAOPERATIVE",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Intravascular =>
                "INTRAVASCULAR",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Musculoskeletal =>
                "MUSCULOSKELETAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.NeonatalHead => "NEONATAL HEAD",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Obstetrical => "OBSTETRICAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Ophthalmic => "OPHTHALMIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pediatric => "PEDIATRIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pelvic => "PELVIC",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Retroperitoneal =>
                "RETROPERITONEAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Scrotal => "SCROTAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.SmallParts => "SMALL PARTS",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tee => "TEE",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Thyroid => "THYROID",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Transcranial => "TRANSCRANIAL",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tte => "TTE",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.UsBiopsy => "US BIOPSY",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Vascular => "VASCULAR",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Isi =>
                "Implemetation Specific Identifiers",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Nmi => "NM Implematation",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Emission => "Emission",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Transmission => "Transmission",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Usi => "US Implemantation",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0001 => "2D Imaging",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0002 => "M-Mode",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0004 => "CW Doppler",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0008 => "PW Doppler",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0010 => "Color Doppler",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0020 => "Color M-Mode",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0040 => "3D Rendering",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0100 => "Color Power Mode",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0200 =>
                "Tissue Characterization",
            Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0400 =>
                "Spatially-related frames",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(
        this Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType value
    ) => new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType"/>, or <c>null</c> if none matches.</returns>
    public static Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType? FromValue(string code) =>
        code switch
        {
            "PDC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pdc,
            "ORIGINAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Original,
            "DERIVED" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Derived,
            "PEC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pec,
            "PRIMARY" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Primary,
            "SECONDARY" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Secondary,
            "MSC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Msc,
            "CT" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Ct,
            "AXIAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Axial,
            "LOCALIZER" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Localizer,
            "MR" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Mr,
            "DENSITYMAP" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Densitymap,
            "DIFFUSIONMAP" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Diffusionmap,
            "IMAGEADDITION" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Imageaddition,
            "MODULUSSUBTRACT" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Modulussubtract,
            "MPR" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Mpr,
            "OTHER" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Other,
            "PHASEMAP" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Phasemap,
            "PHASESUBTRACT" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Phasesubtract,
            "PROJECTIONIMAGE" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Projectionimage,
            "T1MAP" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.T1Map,
            "T2MAP" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.T2Map,
            "VELOCITYMAP" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Velocitymap,
            "NM" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Nm,
            "STATIC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Static,
            "DYNAMIC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Dynamic,
            "GATED" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gated,
            "WHOLEBODY" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Wholebody,
            "TOMO" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tomo,
            "GATEDTOMO" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gatedtomo,
            "RECONTOMO" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Recontomo,
            "RECONGATEDTOMO" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Recongatedtomo,
            "US" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Us,
            "ABDOMINAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Abdominal,
            "BREAST" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Breast,
            "CHEST" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Chest,
            "ENDOCAVITARY" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endocavitary,
            "ENDORECTAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endorectal,
            "ENDOVAGINAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Endovaginal,
            "EPICARDIAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Epicardial,
            "FETAL_HEART" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.FetalHeart,
            "GYNECOLOGY" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Gynecology,
            "INTRACARDIAC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Intracardiac,
            "INTRAOPERATIVE" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Intraoperative,
            "INTRAVASCULAR" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Intravascular,
            "MUSCULOSKELETAL" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Musculoskeletal,
            "NEONATAL_HEAD" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.NeonatalHead,
            "OBSTETRICAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Obstetrical,
            "OPHTHALMIC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Ophthalmic,
            "PEDIATRIC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pediatric,
            "PELVIC" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Pelvic,
            "RETROPERITONEAL" => Bildgebung
                .CodeSystems
                .MiiCsBildgebungInstanceImageType
                .Retroperitoneal,
            "SCROTAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Scrotal,
            "SMALL_PARTS" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.SmallParts,
            "TEE" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tee,
            "THYROID" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Thyroid,
            "TRANSCRANIAL" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Transcranial,
            "TTE" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Tte,
            "US_BIOPSY" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.UsBiopsy,
            "VASCULAR" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Vascular,
            "ISI" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Isi,
            "NMI" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Nmi,
            "EMISSION" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Emission,
            "TRANSMISSION" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Transmission,
            "USI" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType.Usi,
            "0001" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0001,
            "0002" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0002,
            "0004" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0004,
            "0008" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0008,
            "0010" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0010,
            "0020" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0020,
            "0040" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0040,
            "0100" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0100,
            "0200" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0200,
            "0400" => Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType._0400,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Bildgebung.CodeSystems.MiiCsBildgebungInstanceImageType FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for <see cref="Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence"/>.</summary>
public static class MiiCsBildgebungScanningSequenceExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence</c>.</returns>
    public static string Url(this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence _) =>
        "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence value) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Se => "SE",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Ir => "IR",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Gr => "GR",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Ep => "EP",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Rm => "RM",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(
        this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence value
    ) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Se => "Spin Echo",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Ir => "Inversion Recovery",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Gr => "Gradient Recalled",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Ep => "Echo Planar",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Rm => "Research Mode",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(
        this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence value
    ) => new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence"/>, or <c>null</c> if none matches.</returns>
    public static Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence? FromValue(string code) =>
        code switch
        {
            "SE" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Se,
            "IR" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Ir,
            "GR" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Gr,
            "EP" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Ep,
            "RM" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence.Rm,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Bildgebung.CodeSystems.MiiCsBildgebungScanningSequence FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for <see cref="Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant"/>.</summary>
public static class MiiCsBildgebungScanningSequenceVariantExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant</c>.</returns>
    public static string Url(
        this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant _
    ) =>
        "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-scanning-sequence-variant";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(
        this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant value
    ) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Sk => "SK",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Mtc => "MTC",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Ss => "SS",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Trss => "TRSS",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Sp => "SP",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Mp => "MP",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Osp => "OSP",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.None => "NONE",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(
        this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant value
    ) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Sk => "segmented k-space",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Mtc =>
                "magnetization transfer contrast",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Ss => "steady state",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Trss =>
                "time reversed steady state",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Sp => "spoiled",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Mp => "MAG prepared",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Osp =>
                "oversampling phase",
            Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.None =>
                "no sequence variant",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(
        this Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant value
    ) => new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant"/>, or <c>null</c> if none matches.</returns>
    public static Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant? FromValue(
        string code
    ) =>
        code switch
        {
            "SK" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Sk,
            "MTC" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Mtc,
            "SS" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Ss,
            "TRSS" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Trss,
            "SP" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Sp,
            "MP" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Mp,
            "OSP" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.Osp,
            "NONE" => Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant.None,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Bildgebung.CodeSystems.MiiCsBildgebungScanningSequenceVariant FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for <see cref="Bildgebung.CodeSystems.MiiCsBildgebungSeriesType"/>.</summary>
public static class MiiCsBildgebungSeriesTypeExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type</c>.</returns>
    public static string Url(this Bildgebung.CodeSystems.MiiCsBildgebungSeriesType _) =>
        "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-series-type";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Bildgebung.CodeSystems.MiiCsBildgebungSeriesType value) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Static => "STATIC",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Dynamic => "DYNAMIC",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Gated => "GATED",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Wholebody => "WHOLEBODY",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Image => "IMAGE",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Reprojection => "REPROJECTION",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(this Bildgebung.CodeSystems.MiiCsBildgebungSeriesType value) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Static =>
                "a group of images at varying spatial locations at the same time",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Dynamic =>
                "a group of images at a set of spatial locations (e.g., slices) at varying time slices, with all spatial locations acquired at all time slices",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Gated =>
                "a group of images at the same spatial location, same starting and ending time, but acquired in different time slots of (possibly) different R-R intervals",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Wholebody =>
                "same as STATIC, except covering multiple transverse fields of view (and therefore acquired at a different time)",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Image => "a tomographic image slice",
            Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Reprojection =>
                "a projection image derived from forward projection through slices of tomographic images, using the algorithm defined in Reprojection Method (0054,1004)",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Bildgebung.CodeSystems.MiiCsBildgebungSeriesType value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungSeriesType"/>, or <c>null</c> if none matches.</returns>
    public static Bildgebung.CodeSystems.MiiCsBildgebungSeriesType? FromValue(string code) =>
        code switch
        {
            "STATIC" => Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Static,
            "DYNAMIC" => Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Dynamic,
            "GATED" => Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Gated,
            "WHOLEBODY" => Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Wholebody,
            "IMAGE" => Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Image,
            "REPROJECTION" => Bildgebung.CodeSystems.MiiCsBildgebungSeriesType.Reprojection,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungSeriesType"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Bildgebung.CodeSystems.MiiCsBildgebungSeriesType FromValueOrThrow(string code) =>
        FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for <see cref="Bildgebung.CodeSystems.MiiCsBildgebungTransducerType"/>.</summary>
public static class MiiCsBildgebungTransducerTypeExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type</c>.</returns>
    public static string Url(this Bildgebung.CodeSystems.MiiCsBildgebungTransducerType _) =>
        "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/CodeSystem/mii-cs-bildgebung-transducer-type";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Bildgebung.CodeSystems.MiiCsBildgebungTransducerType value) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorPhased => "SECTOR_PHASED",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorMech => "SECTOR_MECH",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorAnnular => "SECTOR_ANNULAR",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.Linear => "LINEAR",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.CurvedLinear => "CURVED_LINEAR",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SingleCrystal => "SINGLE_CRYSTAL",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SplitXtalCwd => "SPLIT_XTAL_CWD",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvPhased => "IV_PHASED",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvRotXtal => "IV_ROT_XTAL",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvRotMirror => "IV_ROT_MIRROR",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavPa => "ENDOCAV_PA",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavMech => "ENDOCAV_MECH",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavCla => "ENDOCAV_CLA",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavAa => "ENDOCAV_AA",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavLinear => "ENDOCAV_LINEAR",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.VectorPhased => "VECTOR_PHASED",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(
        this Bildgebung.CodeSystems.MiiCsBildgebungTransducerType value
    ) =>
        value switch
        {
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorPhased => "Sector Phased",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorMech => "Sector Mech",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorAnnular => "Sector Annular",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.Linear => "Linear",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.CurvedLinear => "Curved Linear",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SingleCrystal => "Single Crystal",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SplitXtalCwd => "Split Xtal CWD",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvPhased => "IV Phased",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvRotXtal => "IV Rot XTAL",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvRotMirror => "IV Rot Mirror",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavPa => "Endocav PA",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavMech => "Endocav Mech",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavCla => "EndocavCLA",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavAa => "Endocav AA",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavLinear => "Endocav Linear",
            Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.VectorPhased => "Vector Phased",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Bildgebung.CodeSystems.MiiCsBildgebungTransducerType value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungTransducerType"/>, or <c>null</c> if none matches.</returns>
    public static Bildgebung.CodeSystems.MiiCsBildgebungTransducerType? FromValue(string code) =>
        code switch
        {
            "SECTOR_PHASED" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorPhased,
            "SECTOR_MECH" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorMech,
            "SECTOR_ANNULAR" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SectorAnnular,
            "LINEAR" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.Linear,
            "CURVED_LINEAR" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.CurvedLinear,
            "SINGLE_CRYSTAL" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SingleCrystal,
            "SPLIT_XTAL_CWD" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.SplitXtalCwd,
            "IV_PHASED" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvPhased,
            "IV_ROT_XTAL" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvRotXtal,
            "IV_ROT_MIRROR" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.IvRotMirror,
            "ENDOCAV_PA" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavPa,
            "ENDOCAV_MECH" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavMech,
            "ENDOCAV_CLA" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavCla,
            "ENDOCAV_AA" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavAa,
            "ENDOCAV_LINEAR" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.EndocavLinear,
            "VECTOR_PHASED" => Bildgebung.CodeSystems.MiiCsBildgebungTransducerType.VectorPhased,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Bildgebung.CodeSystems.MiiCsBildgebungTransducerType"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Bildgebung.CodeSystems.MiiCsBildgebungTransducerType FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for reading <see cref="Bildgebung.Extensions"/> from FHIR resources.</summary>
public static class BildgebungFhirExtensions
{
    /// <summary>Gets the value of extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static FhirString? GetMiiExBildgebungBildgebungsgrund(this IExtendable resource) =>
        resource.GetExtensionValue<FhirString>(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-bildgebungsgrund"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungInstanzDetails(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-instanz-details"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungKontrastmittel(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-kontrastmittel"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungModalitaetCt(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-ct"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungModalitaetMgCrDx(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mg-cr-dx"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungModalitaetMr(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-mr"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungModalitaetNm(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-nm"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungModalitaetPt(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-pt"
        );

    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExBildgebungModalitaetUs(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-modalitaet-us"
        );

    /// <summary>Gets the value of extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Quantity? GetMiiExBildgebungSerieSchichtdicke(this IExtendable resource) =>
        resource.GetExtensionValue<Quantity>(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-serie-schichtdicke"
        );

    /// <summary>Gets the value of extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Id? GetMiiExBildgebungSerieUid(this IExtendable resource) =>
        resource.GetExtensionValue<Id>(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-series-uid"
        );

    /// <summary>Gets the value of extension <c>https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Id? GetMiiExBildgebungSopInstanzUid(this IExtendable resource) =>
        resource.GetExtensionValue<Id>(
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung/StructureDefinition/mii-ex-bildgebung-sop-instanz-uid"
        );
}
