# Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.medikation 2026.0.1.
# Do not edit directly.
from __future__ import annotations

import enum
from typing import Protocol, Self

from fhir.resources.coding import Coding
from fhir.resources.extension import Extension


class _HasExtensions(Protocol):
    extension: list[Extension] | None


class Medikation:
    class CodeSystems:
        MII_CS_MEDIKATION_WIRKSTOFFTYP = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp"

        class MiiCsMedikationWirkstofftyp(enum.Enum):
            """Concepts for https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp."""

            code: str
            display: str | None

            IN = ("IN", "ingredient")
            PIN = ("PIN", "precise ingredient")
            MIN = ("MIN", "multiple ingredients")

            def __init__(self, code: str, display: str | None) -> None:
                self.code = code
                self.display = display

            def url(self) -> str:
                return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp"

            def coding(self) -> Coding:
                return Coding(system=self.url(), code=self.code, display=self.display)

            @classmethod
            def from_value(cls, code: str) -> Self | None:
                for member in cls:
                    if member.code == code:
                        return member
                return None

            @classmethod
            def from_value_or_raise(cls, code: str) -> Self:
                result = cls.from_value(code)
                if result is None:
                    raise ValueError(f"Unknown code: {code!r}")
                return result

    class Profiles:
        MII_PR_MEDIKATION_MEDICATION = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1"

        MII_PR_MEDIKATION_MEDICATION_ADMINISTRATION = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1"

        MII_PR_MEDIKATION_MEDICATION_REQUEST = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1"

        MII_PR_MEDIKATION_MEDICATION_STATEMENT = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1"

        MII_PR_MEDIKATION_MEDIKATIONSLISTE = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1"

    class Extensions:
        MII_EX_MEDIKATION_WIRKSTOFFRELATION = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation"

        MII_EX_MEDIKATION_WIRKSTOFFTYP = "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp"

        @staticmethod
        def mii_ex_medikation_wirkstoffrelation() -> Extension:
            """A new Extension for https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation."""
            return Extension(url="https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation")

        @staticmethod
        def get_mii_ex_medikation_wirkstoffrelation(resource: _HasExtensions) -> Extension | None:
            """Gets the extension https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation from resource, or None if absent."""
            for ext in resource.extension or []:
                if ext.url == "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation":
                    return ext
            return None

        @staticmethod
        def mii_ex_medikation_wirkstofftyp(value: Medikation.CodeSystems.MiiCsMedikationWirkstofftyp) -> Extension:
            """A new Extension for https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp."""
            return Extension(url="https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp", valueCoding=value.coding())

        @staticmethod
        def get_mii_ex_medikation_wirkstofftyp(resource: _HasExtensions) -> Coding | None:
            """Gets the value of extension https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp from resource, or None if absent."""
            for ext in resource.extension or []:
                if ext.url == "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp":
                    return ext.valueCoding
            return None
