"""Tests for python_constants_generator — verifies generated source structure."""

from __future__ import annotations

from ig_codegen.ig_package_model import (
    ConceptConstant,
    ExtensionValueType,
    IgPackageModel,
    NamingSystemEntry,
)
from ig_codegen.python_constants_generator import generate


def _make_model(**overrides) -> IgPackageModel:
    return IgPackageModel(
        package_name=overrides.get("package_name", "de.example.test"),
        package_version=overrides.get("package_version", "1.0.0"),
        code_systems=overrides.get("code_systems", {}),
        profiles=overrides.get("profiles", {}),
        extensions=overrides.get("extensions", {}),
        code_system_concepts=overrides.get("code_system_concepts", {}),
        extension_value_types=overrides.get("extension_value_types", {}),
        naming_systems=overrides.get("naming_systems", {}),
    )


class TestGenerateHeader:
    def test_generated_comment(self) -> None:
        model = _make_model()
        source = generate(model, "Test")
        assert "# Generated by ig-codegen from de.example.test 1.0.0." in source

    def test_future_annotations(self) -> None:
        source = generate(_make_model(), "Test")
        assert "from __future__ import annotations" in source

    def test_no_enum_import_when_no_concepts(self) -> None:
        source = generate(_make_model(), "Test")
        assert "import enum" not in source

    def test_no_protocol_import_when_no_extensions(self) -> None:
        source = generate(_make_model(), "Test")
        assert "from typing import Protocol" not in source

    def test_enum_import_when_concepts_present(self) -> None:
        model = _make_model(
            code_systems={"MII_CS_TEST": "https://example.com/cs"},
            code_system_concepts={
                "MII_CS_TEST": [ConceptConstant("KURATIV", "kurativ", "Kurativ")]
            },
        )
        source = generate(model, "Test")
        assert "import enum" in source

    def test_protocol_import_when_extensions_present(self) -> None:
        model = _make_model(
            extensions={"MII_EX_TEST": "https://example.com/ext"},
        )
        source = generate(model, "Test")
        assert "from typing import Protocol" in source
        assert "class _HasExtensions(Protocol)" in source


class TestCodeSystemsClass:
    def test_url_constant(self) -> None:
        model = _make_model(
            code_systems={"MII_CS_TEST": "https://example.com/cs"},
        )
        source = generate(model, "Test")
        assert "class CodeSystems" in source
        assert 'MII_CS_TEST = "https://example.com/cs"' in source

    def test_enum_class_generated(self) -> None:
        model = _make_model(
            code_systems={"MII_CS_TEST": "https://example.com/cs"},
            code_system_concepts={
                "MII_CS_TEST": [
                    ConceptConstant("KURATIV", "kurativ", "Kurativ"),
                    ConceptConstant("PALLIATIV", "palliativ", None),
                ]
            },
        )
        source = generate(model, "Test")
        assert "class MiiCsTest(enum.Enum)" in source
        assert 'KURATIV = ("kurativ", "Kurativ")' in source
        assert 'PALLIATIV = ("palliativ", None)' in source

    def test_enum_has_coding_import(self) -> None:
        model = _make_model(
            code_systems={"MII_CS_TEST": "https://example.com/cs"},
            code_system_concepts={
                "MII_CS_TEST": [ConceptConstant("KURATIV", "kurativ", "Kurativ")]
            },
        )
        source = generate(model, "Test")
        assert "from fhir.resources.coding import Coding" in source

    def test_enum_methods_present(self) -> None:
        model = _make_model(
            code_systems={"MII_CS_TEST": "https://example.com/cs"},
            code_system_concepts={
                "MII_CS_TEST": [ConceptConstant("KURATIV", "kurativ", "Kurativ")]
            },
        )
        source = generate(model, "Test")
        assert "def url(self) -> str" in source
        assert "def coding(self) -> Coding" in source
        assert "def from_value(cls, code: str)" in source
        assert "def from_value_or_raise(cls, code: str)" in source


class TestProfilesClass:
    def test_profile_constant(self) -> None:
        model = _make_model(profiles={"MII_PR_TEST": "https://example.com/profile|1.0"})
        source = generate(model, "Test")
        assert "class Profiles" in source
        assert 'MII_PR_TEST = "https://example.com/profile|1.0"' in source


class TestExtensionsClass:
    def test_url_constant_and_extension_import(self) -> None:
        model = _make_model(
            extensions={"MII_EX_TEST": "https://example.com/ext"},
        )
        source = generate(model, "Test")
        assert "class Extensions" in source
        assert 'MII_EX_TEST = "https://example.com/ext"' in source
        assert "from fhir.resources.extension import Extension" in source

    def test_primitive_factory_typed(self) -> None:
        model = _make_model(
            extensions={"MII_EX_DECIMAL": "https://example.com/decimal"},
            extension_value_types={
                "MII_EX_DECIMAL": ExtensionValueType.fixed("decimal"),
            },
        )
        source = generate(model, "Test")
        assert "def mii_ex_decimal(value: float) -> Extension" in source
        assert 'return Extension(url="https://example.com/decimal", valueDecimal=value)' in source

    def test_primitive_getter(self) -> None:
        model = _make_model(
            extensions={"MII_EX_DECIMAL": "https://example.com/decimal"},
            extension_value_types={
                "MII_EX_DECIMAL": ExtensionValueType.fixed("decimal"),
            },
        )
        source = generate(model, "Test")
        assert "def get_mii_ex_decimal(resource: _HasExtensions) -> float | None" in source
        assert "return ext.valueDecimal" in source

    def test_string_extension(self) -> None:
        model = _make_model(
            extensions={"MII_EX_STRING": "https://example.com/str"},
            extension_value_types={
                "MII_EX_STRING": ExtensionValueType.fixed("string"),
            },
        )
        source = generate(model, "Test")
        assert "def mii_ex_string(value: str) -> Extension" in source
        assert "def get_mii_ex_string(resource: _HasExtensions) -> str | None" in source

    def test_complex_extension_returns_extension(self) -> None:
        model = _make_model(
            extensions={"MII_EX_COMPLEX": "https://example.com/complex"},
        )
        source = generate(model, "Test")
        assert "def mii_ex_complex() -> Extension" in source
        assert "def get_mii_ex_complex(resource: _HasExtensions) -> Extension | None" in source

    def test_coding_extension_factory(self) -> None:
        model = _make_model(
            extensions={"MII_EX_CODING": "https://example.com/coding"},
            extension_value_types={
                "MII_EX_CODING": ExtensionValueType.fixed("Coding"),
            },
        )
        source = generate(model, "Test")
        assert "from fhir.resources.coding import Coding" in source
        assert "def mii_ex_coding(value: Coding) -> Extension" in source
        assert "def get_mii_ex_coding(resource: _HasExtensions) -> Coding | None" in source

    def test_bound_coding_factory(self) -> None:
        model = _make_model(
            code_systems={"MII_CS_STATUS": "https://example.com/cs-status"},
            code_system_concepts={
                "MII_CS_STATUS": [ConceptConstant("A", "a", "A")],
            },
            extensions={"MII_EX_STATUS": "https://example.com/ext-status"},
            extension_value_types={
                "MII_EX_STATUS": ExtensionValueType.bound_coding(
                    "Coding", "https://example.com/cs-status"
                ),
            },
        )
        source = generate(model, "Test")
        assert "def mii_ex_status(value: Test.CodeSystems.MiiCsStatus) -> Extension" in source
        assert "valueCoding=value.coding()" in source

    def test_bound_codeable_concept_factory(self) -> None:
        model = _make_model(
            code_systems={"MII_CS_STATUS": "https://example.com/cs-status"},
            code_system_concepts={
                "MII_CS_STATUS": [ConceptConstant("A", "a", "A")],
            },
            extensions={"MII_EX_STATUS": "https://example.com/ext-status"},
            extension_value_types={
                "MII_EX_STATUS": ExtensionValueType.bound_coding(
                    "CodeableConcept", "https://example.com/cs-status"
                ),
            },
        )
        source = generate(model, "Test")
        assert "def mii_ex_status(value: Test.CodeSystems.MiiCsStatus) -> Extension" in source
        assert "valueCodeableConcept=CodeableConcept(coding=[value.coding()])" in source

    def test_has_extensions_protocol(self) -> None:
        model = _make_model(
            extensions={"MII_EX_TEST": "https://example.com/ext"},
        )
        source = generate(model, "Test")
        assert "class _HasExtensions(Protocol)" in source
        assert "extension: list[Extension] | None" in source


class TestNamingSystemsClass:
    def test_naming_system_generated(self) -> None:
        model = _make_model(
            naming_systems={
                "RESEARCH_SUBJECT_ID": NamingSystemEntry(
                    description="Research subject identifier",
                    by_type={"uri": ["https://example.com/ns"], "oid": ["2.16.123"]},
                )
            }
        )
        source = generate(model, "Test")
        assert "class NamingSystems" in source
        assert "class ResearchSubjectId" in source
        assert 'uri = "https://example.com/ns"' in source
        assert 'oid = "2.16.123"' in source

    def test_multiple_values_become_list(self) -> None:
        model = _make_model(
            naming_systems={
                "NS_MULTI": NamingSystemEntry(
                    description=None,
                    by_type={"uri": ["https://a.com", "https://b.com"]},
                )
            }
        )
        source = generate(model, "Test")
        assert '"https://a.com", "https://b.com"' in source


class TestMainClassStructure:
    def test_main_class_present(self) -> None:
        source = generate(_make_model(), "MyClass")
        assert "class MyClass" in source

    def test_empty_model_has_pass(self) -> None:
        source = generate(_make_model(), "MyClass")
        assert "pass" in source
