# Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.icu 2026.0.2.
# Do not edit directly.
from __future__ import annotations


class Icu:
    class Profiles:
        MII_ICU_VENT_INSPIRATORISCHE_SAUERSTOFFFRAKTION_EINGESTELLT = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorische-sauerstofffraktion-eingestellt|2026.0.2"
        )

        MII_PR_ICU_BILANZ = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_BLUTVERLUST = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-blutverlust|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_DRAINAGE_GENERISCH = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-drainage-generisch|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_FLUESSIGKEIT_GESAMT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_GALLENFLUESSIGKEIT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_HAEMOFILTRATION_EINZELMESSWERTE = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-haemofiltration-einzelmesswerte|2026.0.2"
        )

        MII_PR_ICU_BILANZ_AUSFUHR_MAGENSONDE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-magensonde|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_OP_DRAINAGE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-op-drainage|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_PANKREASDRAINAGE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-pankreasdrainage|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_STUHLGANG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-stuhlgang|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_URIN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-urin|2026.0.2"

        MII_PR_ICU_BILANZ_AUSFUHR_WUNDDRAINAGE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-wunddrainage|2026.0.2"

        MII_PR_ICU_BILANZ_EINFUHR_ENTERALE_FLUESSIGKEIT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit|2026.0.2"

        MII_PR_ICU_BILANZ_EINFUHR_FLUESSIGKEIT_GESAMT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt|2026.0.2"

        MII_PR_ICU_BILANZ_TAGESBILANZ_FLUESSIGKEIT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-tagesbilanz-fluessigkeit|2026.0.2"

        MII_PR_ICU_DEVICE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-icu-device|2026.0.2"

        MII_PR_ICU_ECT_ARTERIELLER_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-arterieller-druck|2026.0.2"

        MII_PR_ICU_ECT_BLUTFLUSSINDEX_EXTRAKORPORALER_GASAUSTAUSCH = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutflussindex-extrakorporaler-gasaustausch|2026.0.2"
        )

        MII_PR_ICU_ECT_BLUTFLUSS_CARDIOVASCULAERES_GERAET = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutfluss-cardiovasculaeres-geraet|2026.0.2"

        MII_PR_ICU_ECT_BLUTFLUSS_EXTRAKORPORALER_GASAUSTAUSCH = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-blutfluss-extrakorporaler-gasaustausch|2026.0.2"
        )

        MII_PR_ICU_ECT_DAUER_EXTRAKORPORALER_GASAUSTAUSCH = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dauer-extrakorporaler-gasaustausch|2026.0.2"

        MII_PR_ICU_ECT_DAUER_HAEMODIALYSESITZUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dauer-haemodialysesitzung|2026.0.2"

        MII_PR_ICU_ECT_DM_EINGEST_GEM_PARAMETER_EXTRAKORPORALE_VERFAHREN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-extrakorporale-verfahren|2026.0.2"
        )

        MII_PR_ICU_ECT_EXTRAKORPORALES_VERFAHREN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-extrakorporales-verfahren|2026.0.2"

        MII_PR_ICU_ECT_GASFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-gasfluss|2026.0.2"

        MII_PR_ICU_ECT_HAEMODIALYSE_BLUTFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-haemodialyse-blutfluss|2026.0.2"

        MII_PR_ICU_ECT_ONISIERTES_KALZIUM_NIERENERSATZVERFAHREN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ionisiertes-kalzium-nierenersatzverfahren|2026.0.2"
        )

        MII_PR_ICU_ECT_PARAMETER_VON_EXTRAKORPORALEN_VERFAHREN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-extrakorporalen-verfahren|2026.0.2"
        )

        MII_PR_ICU_ECT_SUBSTITUATFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-substituatfluss|2026.0.2"

        MII_PR_ICU_ECT_SUBSTITUATVOLUMEN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-substituatvolumen|2026.0.2"

        MII_PR_ICU_ECT_VENOESER_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-venoeser-druck|2026.0.2"

        MII_PR_ICU_EVENT_XSPIRATORISCHER_SAUERSTOFFPARTIALDRUCK = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-exspiratorischer-sauerstoffpartialdruck|2026.0.2"
        )

        MII_PR_ICU_MUV_ARTERIELLER_BLUTDRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-arterieller-blutdruck|2026.0.2"

        MII_PR_ICU_MUV_ATEMFREQUENZ = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-atemfrequenz|2026.0.2"

        MII_PR_ICU_MUV_HERZFREQUENZ = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-herzfrequenz|2026.0.2"

        MII_PR_ICU_MUV_KOERPERGEWICHT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2026.0.2"

        MII_PR_ICU_MUV_KOERPERGROESSE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2026.0.2"

        MII_PR_ICU_MUV_KOPFUMFANG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-kopfumfang|2026.0.2"

        MII_PR_ICU_VENT_ATEMWEGSDRUCK_BEI_NULL_EXPIRATORISCHEM_GASFLUSS = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemwegsdruck-bei-null-expiratorischem-gasfluss|2026.0.2"
        )

        MII_PR_ICU_VENT_ATEMWEGSDRUCK_MITTLEREM_EXPIRATORISCHEM_GASFLUSS = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss|2026.0.2"
        )

        MII_PR_ICU_VENT_ATEMZUGVOLUMEN_EINSTELLUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemzugvolumen-einstellung|2026.0.2"

        MII_PR_ICU_VENT_ATEMZUGVOLUMEN_WAEHREND_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-atemzugvolumen-waehrend-beatmung|2026.0.2"

        MII_PR_ICU_VENT_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmung|2026.0.2"

        MII_PR_ICU_VENT_BEATMUNGSVOLUMEN_MIN_MASCHINELLER_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungsvolumen-pro-minute-maschineller-beatmung|2026.0.2"
        )

        MII_PR_ICU_VENT_BEATMUNGSZEIT_HOHEM_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungszeit-hohem-druck|2026.0.2"

        MII_PR_ICU_VENT_BEATMUNGSZEIT_NIEDRIGEM_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmungszeit-niedrigem-druck|2026.0.2"

        MII_PR_ICU_VENT_DM_EINGESTELLTE_GEMESSENE_PARAMETER_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-beatmung|2026.0.2"
        )

        MII_PR_ICU_VENT_EINGESTELLTER_INSPIRATORISCHER_GASFLUSS = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-eingestellter-inspiratorischer-gasfluss|2026.0.2"
        )

        MII_PR_ICU_VENT_EINSTELLUNG_AUSATMUNGSZEIT_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-einstellung-ausatmungszeit-beatmung|2026.0.2"
        )

        MII_PR_ICU_VENT_EINSTELLUNG_EINATMUNGSZEIT_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-einstellung-einatmungszeit-beatmung|2026.0.2"
        )

        MII_PR_ICU_VENT_ENDEXPIRATORISCHER_KOHLENDIOXIDPARTIALDRUCK = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-endexpiratorischer-kohlendioxidpartialdruck|2026.0.2"
        )

        MII_PR_ICU_VENT_EXSPIRATORISCHER_GASFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-exspiratorischer-gasfluss|2026.0.2"

        MII_PR_ICU_VENT_HOROWITZ_IN_ARTERIELLEM_BLUT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-horowitz-in-arteriellem-blut|2026.0.2"

        MII_PR_ICU_VENT_INSPIRATORISCHER_GASFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorischer-gasfluss|2026.0.2"

        MII_PR_ICU_VENT_INSPIRATORISCHE_SAUERSTOFFFRAKTION_GEMESSEN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-inspiratorische-sauerstofffraktion-gemessen|2026.0.2"
        )

        MII_PR_ICU_VENT_MAXIMALER_BEATMUNGSDRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-maximaler-beatmungsdruck|2026.0.2"

        MII_PR_ICU_VENT_MECHANISCHE_ATEMFREQUENZ_BEATMET = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-mechanische-atemfrequenz-beatmet|2026.0.2"

        MII_PR_ICU_VENT_MITTLERER_BEATMUNGSDRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-mittlerer-beatmungsdruck|2026.0.2"

        MII_PR_ICU_VENT_POSITIV_ENDEXPIRATORISCHER_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-positiv-endexpiratorischer-druck|2026.0.2"

        MII_PR_ICU_VENT_SPONTANES_ATEMZUGVOLUMEN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontanes-atemzugvolumen|2026.0.2"

        MII_PR_ICU_VENT_SPONTANES_PLUS_MECHANISCHES_ATEMZUGVOLUMEN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontanes-mechanisches-atemzugvolumen-waehrend-beatmung|2026.0.2"
        )

        MII_PR_ICU_VENT_SPONTANE_ATEMFREQUENZ_BEATMET = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontane-atemfrequenz-beatmet|2026.0.2"

        MII_PR_ICU_VENT_SPONTANE_MECHANISCHE_ATEMFREQUENZ_BEATMET = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-spontane-mechanische-atemfrequenz-beatmet|2026.0.2"
        )

        MII_PR_ICU_VENT_UNTERSTUEZUNGSDRUCK_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-unterstuetzungsdruck-beatmung|2026.0.2"

        MII_PR_ICU_VENT_ZEITVERHAELTNIS_EIN_AUSATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-zeitverhaeltnis-ein-ausatmung|2026.0.2"

        MII_PR_VENT_ICU_DYNAMISCHE_KOMPLIANCE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dynamische-kompliance|2026.0.2"

        MII_PR_VENT_ICU_PARAMETER_VON_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-beatmung|2026.0.2"

        MII_PR_VENT_PROVIDED_ICU_DRUCKDIFFERENZ_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-druckdifferenz-beatmung|2026.0.2"
