# Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.icu 2027.0.0-ballot.rc2.
# Do not edit directly.
from __future__ import annotations


class Icu:
    class Profiles:
        MII_PR_ICU_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmung|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_AUSFUHR_BLUTVERLUST = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-blutverlust|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_AUSFUHR_DRAINAGE_GENERISCH = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-drainage-generisch|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_BILANZ_AUSFUHR_FLUESSIGKEIT_GESAMT = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_BILANZ_AUSFUHR_GALLENFLUESSIGKEIT = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_BILANZ_AUSFUHR_HAEMOFILTRATION_EINZELMESSWERTE = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-haemofiltration-einzelmesswerte|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_BILANZ_AUSFUHR_MAGENSONDE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-magensonde|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_AUSFUHR_OP_DRAINAGE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-op-drainage|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_AUSFUHR_PANKREASDRAINAGE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-pankreasdrainage|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_AUSFUHR_STUHLGANG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-stuhlgang|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_AUSFUHR_URIN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-urin|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_AUSFUHR_WUNDDRAINAGE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-wunddrainage|2027.0.0-ballot.rc1"

        MII_PR_ICU_BILANZ_EINFUHR_ENTERALE_FLUESSIGKEIT = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_BILANZ_EINFUHR_FLUESSIGKEIT_GESAMT = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_BILANZ_TAGESBILANZ_FLUESSIGKEIT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-tagesbilanz-fluessigkeit|2027.0.0-ballot.rc1"

        MII_PR_ICU_DEVICE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-device|2027.0.0-ballot.rc1"

        MII_PR_ICU_DM_EINGESTELLTE_GEMESSENE_PARAMETER_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingestellte-gemessene-parameter-beatmung|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_DM_EINGEST_GEM_PARAMETER_EXTRAKORPORALE_VERFAHREN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingest-gem-parameter-extrakorporale-verfahren|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_ECT_ARTERIELLER_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-arterieller-druck|2027.0.0-ballot.rc1"

        MII_PR_ICU_ECT_BLUTFLUSSINDEX_EXTRAKORPORALER_GASAUSTAUSCH = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutflussindex-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_ECT_BLUTFLUSS_CARDIOVASCULAERES_GERAET = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-cardiovasculaeres-geraet|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_ECT_BLUTFLUSS_EXTRAKORPORALER_GASAUSTAUSCH = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_ECT_DAUER_EXTRAKORPORALER_GASAUSTAUSCH = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_ECT_DAUER_HAEMODIALYSESITZUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-haemodialysesitzung|2027.0.0-ballot.rc1"

        MII_PR_ICU_ECT_GASFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-gasfluss|2027.0.0-ballot.rc1"

        MII_PR_ICU_ECT_HAEMODIALYSE_BLUTFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-haemodialyse-blutfluss|2027.0.0-ballot.rc1"

        MII_PR_ICU_ECT_IONISIERTES_KALZIUM_NIERENERSATZVERFAHREN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-ionisiertes-kalzium-nierenersatzverfahren|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_ECT_SUBSTITUATFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatfluss|2027.0.0-ballot.rc1"

        MII_PR_ICU_ECT_SUBSTITUATVOLUMEN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatvolumen|2027.0.0-ballot.rc1"

        MII_PR_ICU_ECT_VENOESER_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-venoeser-druck|2027.0.0-ballot.rc1"

        MII_PR_ICU_EXTRAKORPORALES_VERFAHREN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-extrakorporales-verfahren|2027.0.0-ballot.rc1"

        MII_PR_ICU_MUV_ARTERIELLER_BLUTDRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-arterieller-blutdruck|2027.0.0-ballot.rc1"

        MII_PR_ICU_MUV_ATEMFREQUENZ = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-atemfrequenz|2027.0.0-ballot.rc1"

        MII_PR_ICU_MUV_HERZFREQUENZ = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-herzfrequenz|2026.0.2"

        MII_PR_ICU_MUV_KOERPERGEWICHT = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2027.0.0-ballot.rc1"

        MII_PR_ICU_MUV_KOERPERGROESSE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2027.0.0-ballot.rc1"

        MII_PR_ICU_MUV_KOERPERLAENGE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerperlaenge|2026.0.2"

        MII_PR_ICU_MUV_KOPFUMFANG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-kopfumfang|2027.0.0-ballot.rc1"

        MII_PR_ICU_PARAMETER_VON_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-beatmung|2027.0.0-ballot.rc1"

        MII_PR_ICU_PARAMETER_VON_EXTRAKORPORALEN_VERFAHREN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-extrakorporalen-verfahren|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_SCORE_FACES_PAIN_SCALE_REVISED = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-faces-pain-scale-revised|2026.0.0"

        MII_PR_ICU_SCORE_GCS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-gcs|2026.0.0"

        MII_PR_ICU_SCORE_NUMERISCHE_RATINGSKALA = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-numerische-ratingskala|2026.0.0"

        MII_PR_ICU_SCORE_RASS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-rass|2026.0.0"

        MII_PR_ICU_SCORE_VISUELLE_ANALOGSKALA = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-visuelle-analogskala|2026.0.0"

        MII_PR_ICU_VENT_ATEMWEGSDRUCK_BEI_NULL_EXPIRATORISCHEM_GASFLUSS = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-null-expiratorischem-gasfluss|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_ATEMWEGSDRUCK_MITTLEREM_EXPIRATORISCHEM_GASFLUSS = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_ATEMZUGVOLUMEN_EINSTELLUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-einstellung|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_ATEMZUGVOLUMEN_WAEHREND_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_BEATMUNGSVOLUMEN_MIN_MASCHINELLER_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungsvolumen-pro-minute-maschineller-beatmung|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_BEATMUNGSZEIT_HOHEM_DRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-hohem-druck|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_BEATMUNGSZEIT_NIEDRIGEM_DRUCK = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-niedrigem-druck|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_DRUCKDIFFERENZ_BEATMUNG = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-druckdifferenz-beatmung|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_DYNAMISCHE_KOMPLIANCE = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-dynamische-kompliance|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_EINGESTELLTER_INSPIRATORISCHER_GASFLUSS = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-eingestellter-inspiratorischer-gasfluss|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_EINSTELLUNG_AUSATMUNGSZEIT_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-ausatmungszeit-beatmung|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_EINSTELLUNG_EINATMUNGSZEIT_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-einatmungszeit-beatmung|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_ENDEXPIRATORISCHER_KOHLENDIOXIDPARTIALDRUCK = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-endexpiratorischer-kohlendioxidpartialdruck|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_EXSPIRATORISCHER_GASFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-gasfluss|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_EXSPIRATORISCHER_SAUERSTOFFPARTIALDRUCK = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-sauerstoffpartialdruck|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_HOROWITZ_IN_ARTERIELLEM_BLUT = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-horowitz-in-arteriellem-blut|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_INSPIRATORISCHER_GASFLUSS = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorischer-gasfluss|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_INSPIRATORISCHE_SAUERSTOFFFRAKTION = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorische-sauerstofffraktion|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_MAXIMALER_BEATMUNGSDRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-maximaler-beatmungsdruck|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_MECHANISCHE_ATEMFREQUENZ_BEATMET = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_MITTLERER_INSPIRATORISCHER_BEATMUNGSDRUCK = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mittlerer-inspiratorischer-beatmungsdruck|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_PLATEAU_BEATMUNGSDRUCK = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-plateau-beatmungsdruck|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_POSITIV_ENDEXPIRATORISCHER_DRUCK = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-positiv-endexpiratorischer-druck|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_SPONTANES_ATEMZUGVOLUMEN = "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-atemzugvolumen|2027.0.0-ballot.rc1"

        MII_PR_ICU_VENT_SPONTANES_PLUS_MECHANISCHES_ATEMZUGVOLUMEN = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-mechanisches-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_SPONTANE_ATEMFREQUENZ_BEATMET = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-atemfrequenz-beatmet|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_SPONTANE_MECHANISCHE_ATEMFREQUENZ_BEATMET = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_UNTERSTUETZUNGSDRUCK_BEATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-unterstuetzungsdruck-beatmung|2027.0.0-ballot.rc1"
        )

        MII_PR_ICU_VENT_ZEITVERHAELTNIS_EIN_AUSATMUNG = (
            "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-zeitverhaeltnis-ein-ausatmung|2027.0.0-ballot.rc1"
        )
