// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.medikation 2026.0.1. Do
// not edit directly.
package de.medizininformatikinitiative.kerndatensatz.medikation;

public final class Medikation {
  private Medikation() {}

  public static final class CodeSystems {
    private CodeSystems() {}

    public static String miiCsMedikationWirkstofftyp() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp";
    }
  }

  public static final class Profiles {
    private Profiles() {}

    public static String miiPrMedikationMedication() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1";
    }

    public static String miiPrMedikationMedicationAdministration() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1";
    }

    public static String miiPrMedikationMedicationRequest() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1";
    }

    public static String miiPrMedikationMedicationStatement() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1";
    }

    public static String miiPrMedikationMedikationsliste() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1";
    }
  }

  public static final class Extensions {
    private Extensions() {}

    public static String miiExMedikationWirkstoffrelation() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation";
    }

    public static String miiExMedikationWirkstofftyp() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp";
    }
  }
}
