// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.medikation 2026.0.1. Do
// not edit directly.
package de.medizininformatikinitiative.kerndatensatz.medikation;

import java.util.Optional;
import org.hl7.fhir.r4.model.Coding;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

public final class Medikation {
  private Medikation() {}

  public static final class CodeSystems {
    private CodeSystems() {}

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp}
     */
    public static String miiCsMedikationWirkstofftyp() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp";
    }

    public enum MiiCsMedikationWirkstofftyp {
      /** {@code IN} - ingredient */
      IN("IN", "ingredient"),

      /** {@code PIN} - precise ingredient */
      PIN("PIN", "precise ingredient"),

      /** {@code MIN} - multiple ingredients */
      MIN("MIN", "multiple ingredients");

      private final @NonNull String code;

      private final @Nullable String display;

      MiiCsMedikationWirkstofftyp(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code
       *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp}
       */
      public @NonNull Coding coding(@NonNull MiiCsMedikationWirkstofftyp this) {
        return new Coding(
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp",
            code,
            display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if
       *     none matches
       */
      public static Optional<@NonNull MiiCsMedikationWirkstofftyp> fromValue(@NonNull String code) {
        for (MiiCsMedikationWirkstofftyp value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }
    }
  }

  public static final class Profiles {
    private Profiles() {}

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1}
     */
    public static String miiPrMedikationMedication() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1}
     */
    public static String miiPrMedikationMedicationAdministration() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1}
     */
    public static String miiPrMedikationMedicationRequest() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1}
     */
    public static String miiPrMedikationMedicationStatement() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1}
     */
    public static String miiPrMedikationMedikationsliste() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1";
    }
  }

  public static final class Extensions {
    private Extensions() {}

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation}
     */
    public static String miiExMedikationWirkstoffrelation() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp}
     */
    public static String miiExMedikationWirkstofftyp() {
      return "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp";
    }
  }
}
