// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.icu
// 2027.0.0-ballot.rc2. Do not edit directly.
package de.medizininformatikinitiative.kerndatensatz.icu;

public final class Icu {
  private Icu() {}

  public static final class Profiles {
    private Profiles() {}

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanz() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-blutverlust|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-blutverlust|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrBlutverlust() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-blutverlust|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-drainage-generisch|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-drainage-generisch|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrDrainageGenerisch() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-drainage-generisch|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrFluessigkeitGesamt() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrGallenfluessigkeit() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-haemofiltration-einzelmesswerte|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-haemofiltration-einzelmesswerte|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrHaemofiltrationEinzelmesswerte() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-haemofiltration-einzelmesswerte|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-magensonde|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-magensonde|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrMagensonde() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-magensonde|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-op-drainage|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-op-drainage|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrOpDrainage() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-op-drainage|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-pankreasdrainage|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-pankreasdrainage|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrPankreasdrainage() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-pankreasdrainage|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-stuhlgang|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-stuhlgang|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrStuhlgang() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-stuhlgang|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-urin|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-urin|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrUrin() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-urin|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-wunddrainage|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-wunddrainage|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzAusfuhrWunddrainage() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-ausfuhr-wunddrainage|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzEinfuhrEnteraleFluessigkeit() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzEinfuhrFluessigkeitGesamt() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-tagesbilanz-fluessigkeit|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-tagesbilanz-fluessigkeit|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuBilanzTagesbilanzFluessigkeit() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-bilanz-tagesbilanz-fluessigkeit|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-device|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-device|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuDevice() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-device|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingestellte-gemessene-parameter-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingestellte-gemessene-parameter-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuDmEingestellteGemesseneParameterBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingestellte-gemessene-parameter-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingest-gem-parameter-extrakorporale-verfahren|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingest-gem-parameter-extrakorporale-verfahren|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuDmEingestGemParameterExtrakorporaleVerfahren() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-dm-eingest-gem-parameter-extrakorporale-verfahren|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-arterieller-druck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-arterieller-druck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctArteriellerDruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-arterieller-druck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutflussindex-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutflussindex-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctBlutflussindexExtrakorporalerGasaustausch() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutflussindex-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-cardiovasculaeres-geraet|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-cardiovasculaeres-geraet|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctBlutflussCardiovasculaeresGeraet() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-cardiovasculaeres-geraet|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctBlutflussExtrakorporalerGasaustausch() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-blutfluss-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctDauerExtrakorporalerGasaustausch() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-extrakorporaler-gasaustausch|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-haemodialysesitzung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-haemodialysesitzung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctDauerHaemodialysesitzung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-dauer-haemodialysesitzung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-gasfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-gasfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctGasfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-gasfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-haemodialyse-blutfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-haemodialyse-blutfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctHaemodialyseBlutfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-haemodialyse-blutfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-ionisiertes-kalzium-nierenersatzverfahren|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-ionisiertes-kalzium-nierenersatzverfahren|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctIonisiertesKalziumNierenersatzverfahren() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-ionisiertes-kalzium-nierenersatzverfahren|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctSubstituatfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatvolumen|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatvolumen|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctSubstituatvolumen() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-substituatvolumen|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-venoeser-druck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-venoeser-druck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuEctVenoeserDruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-ect-venoeser-druck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-extrakorporales-verfahren|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-extrakorporales-verfahren|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuExtrakorporalesVerfahren() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-extrakorporales-verfahren|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-arterieller-blutdruck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-arterieller-blutdruck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuMuvArteriellerBlutdruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-arterieller-blutdruck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-atemfrequenz|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-atemfrequenz|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuMuvAtemfrequenz() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-atemfrequenz|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-herzfrequenz|2026.0.2}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-herzfrequenz|2026.0.2}
     */
    public static String miiPrIcuMuvHerzfrequenz() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-herzfrequenz|2026.0.2";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuMuvKoerpergewicht() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuMuvKoerpergroesse() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerperlaenge|2026.0.2}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerperlaenge|2026.0.2}
     */
    public static String miiPrIcuMuvKoerperlaenge() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerperlaenge|2026.0.2";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-kopfumfang|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-kopfumfang|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuMuvKopfumfang() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-kopfumfang|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuParameterVonBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-extrakorporalen-verfahren|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-extrakorporalen-verfahren|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuParameterVonExtrakorporalenVerfahren() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-parameter-von-extrakorporalen-verfahren|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-faces-pain-scale-revised|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-faces-pain-scale-revised|2026.0.0}
     */
    public static String miiPrIcuScoreFacesPainScaleRevised() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-faces-pain-scale-revised|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-gcs|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-gcs|2026.0.0}
     */
    public static String miiPrIcuScoreGcs() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-gcs|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-numerische-ratingskala|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-numerische-ratingskala|2026.0.0}
     */
    public static String miiPrIcuScoreNumerischeRatingskala() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-numerische-ratingskala|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-rass|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-rass|2026.0.0}
     */
    public static String miiPrIcuScoreRass() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-rass|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-visuelle-analogskala|2026.0.0}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-visuelle-analogskala|2026.0.0}
     */
    public static String miiPrIcuScoreVisuelleAnalogskala() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-score-visuelle-analogskala|2026.0.0";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-null-expiratorischem-gasfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-null-expiratorischem-gasfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentAtemwegsdruckBeiNullExpiratorischemGasfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-null-expiratorischem-gasfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentAtemwegsdruckMittleremExpiratorischemGasfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-einstellung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-einstellung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentAtemzugvolumenEinstellung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-einstellung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentAtemzugvolumenWaehrendBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungsvolumen-pro-minute-maschineller-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungsvolumen-pro-minute-maschineller-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentBeatmungsvolumenMinMaschinellerBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungsvolumen-pro-minute-maschineller-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-hohem-druck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-hohem-druck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentBeatmungszeitHohemDruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-hohem-druck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-niedrigem-druck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-niedrigem-druck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentBeatmungszeitNiedrigemDruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-beatmungszeit-niedrigem-druck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-druckdifferenz-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-druckdifferenz-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentDruckdifferenzBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-druckdifferenz-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-dynamische-kompliance|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-dynamische-kompliance|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentDynamischeKompliance() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-dynamische-kompliance|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-eingestellter-inspiratorischer-gasfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-eingestellter-inspiratorischer-gasfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentEingestellterInspiratorischerGasfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-eingestellter-inspiratorischer-gasfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-ausatmungszeit-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-ausatmungszeit-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentEinstellungAusatmungszeitBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-ausatmungszeit-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-einatmungszeit-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-einatmungszeit-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentEinstellungEinatmungszeitBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-einstellung-einatmungszeit-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-endexpiratorischer-kohlendioxidpartialdruck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-endexpiratorischer-kohlendioxidpartialdruck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentEndexpiratorischerKohlendioxidpartialdruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-endexpiratorischer-kohlendioxidpartialdruck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-gasfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-gasfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentExspiratorischerGasfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-gasfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-sauerstoffpartialdruck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-sauerstoffpartialdruck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentExspiratorischerSauerstoffpartialdruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-exspiratorischer-sauerstoffpartialdruck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-horowitz-in-arteriellem-blut|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-horowitz-in-arteriellem-blut|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentHorowitzInArteriellemBlut() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-horowitz-in-arteriellem-blut|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorischer-gasfluss|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorischer-gasfluss|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentInspiratorischerGasfluss() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorischer-gasfluss|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorische-sauerstofffraktion|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorische-sauerstofffraktion|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentInspiratorischeSauerstofffraktion() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-inspiratorische-sauerstofffraktion|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-maximaler-beatmungsdruck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-maximaler-beatmungsdruck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentMaximalerBeatmungsdruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-maximaler-beatmungsdruck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentMechanischeAtemfrequenzBeatmet() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mittlerer-inspiratorischer-beatmungsdruck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mittlerer-inspiratorischer-beatmungsdruck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentMittlererInspiratorischerBeatmungsdruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-mittlerer-inspiratorischer-beatmungsdruck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-plateau-beatmungsdruck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-plateau-beatmungsdruck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentPlateauBeatmungsdruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-plateau-beatmungsdruck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-positiv-endexpiratorischer-druck|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-positiv-endexpiratorischer-druck|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentPositivEndexpiratorischerDruck() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-positiv-endexpiratorischer-druck|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-atemzugvolumen|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-atemzugvolumen|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentSpontanesAtemzugvolumen() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-atemzugvolumen|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-mechanisches-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-mechanisches-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentSpontanesPlusMechanischesAtemzugvolumen() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontanes-mechanisches-atemzugvolumen-waehrend-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-atemfrequenz-beatmet|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-atemfrequenz-beatmet|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentSpontaneAtemfrequenzBeatmet() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-atemfrequenz-beatmet|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentSpontaneMechanischeAtemfrequenzBeatmet() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-spontane-mechanische-atemfrequenz-beatmet|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-unterstuetzungsdruck-beatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-unterstuetzungsdruck-beatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentUnterstuetzungsdruckBeatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-unterstuetzungsdruck-beatmung|2027.0.0-ballot.rc1";
    }

    /**
     * The canonical URL {@code
     * https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-zeitverhaeltnis-ein-ausatmung|2027.0.0-ballot.rc1}.
     *
     * @return {@code
     *     https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-zeitverhaeltnis-ein-ausatmung|2027.0.0-ballot.rc1}
     */
    public static String miiPrIcuVentZeitverhaeltnisEinAusatmung() {
      return "https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-vent-zeitverhaeltnis-ein-ausatmung|2027.0.0-ballot.rc1";
    }
  }
}
