// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.medikation 2027.0.0-ballot. Do not edit directly.
using Hl7.Fhir.Model;

namespace De.Medizininformatikinitiative.Kerndatensatz.Medikation;

public static class Medikation
{
    public static class CodeSystems
    {
        public static class Urls
        {
            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/mii-cs-medikation-pzn-sales-status-code</c>.</summary>
            public static string MiiCsMedikationPznSalesStatusCode =>
                "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/mii-cs-medikation-pzn-sales-status-code";

            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp</c>.</summary>
            public static string MiiCsMedikationWirkstofftyp =>
                "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp";
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/mii-cs-medikation-pzn-sales-status-code</c>.</summary>
        public enum MiiCsMedikationPznSalesStatusCode
        {
            /// <summary><c>D</c> - Wegfall</summary>
            D,

            /// <summary><c>F</c> - Außer Vertrieb</summary>
            F,

            /// <summary><c>N</c> - Im Vertrieb</summary>
            N,

            /// <summary><c>R</c> - Rückruf</summary>
            R,

            /// <summary><c>Z</c> - Zurückgezogen</summary>
            Z,
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp</c>.</summary>
        public enum MiiCsMedikationWirkstofftyp
        {
            /// <summary><c>IN</c> - ingredient</summary>
            In,

            /// <summary><c>PIN</c> - precise ingredient</summary>
            Pin,

            /// <summary><c>MIN</c> - multiple ingredients</summary>
            Min,
        }
    }

    public static class Profiles
    {
        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2027.0.0-ballot</c>.</summary>
        public static string MiiPrMedikationMedication =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2027.0.0-ballot";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2027.0.0-ballot</c>.</summary>
        public static string MiiPrMedikationMedicationAdministration =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2027.0.0-ballot";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2027.0.0-ballot</c>.</summary>
        public static string MiiPrMedikationMedicationRequest =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2027.0.0-ballot";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2027.0.0-ballot</c>.</summary>
        public static string MiiPrMedikationMedicationStatement =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2027.0.0-ballot";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2027.0.0-ballot</c>.</summary>
        public static string MiiPrMedikationMedikationsliste =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2027.0.0-ballot";
    }

    public static class Extensions
    {
        public static class Urls
        {
            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation</c>.</summary>
            public static string MiiExMedikationWirkstoffrelation =>
                "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation";

            /// <summary>The extension URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp</c>.</summary>
            public static string MiiExMedikationWirkstofftyp =>
                "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp";
        }

        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation</c> and no value.</returns>
        public static Extension MiiExMedikationWirkstoffrelation() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation",
            };

        /// <summary>A new <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp</c>.</summary>
        /// <param name="value">The extension value, as a <c>MiiCsMedikationWirkstofftyp</c> concept.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp</c> and the given value.</returns>
        public static Extension MiiExMedikationWirkstofftyp(
            CodeSystems.MiiCsMedikationWirkstofftyp value
        ) =>
            new(
                "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp",
                value.Coding()
            );
    }
}

/// <summary>Extension methods for <see cref="Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode"/>.</summary>
public static class MiiCsMedikationPznSalesStatusCodeExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/mii-cs-medikation-pzn-sales-status-code</c>.</returns>
    public static string Url(this Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode _) =>
        "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/mii-cs-medikation-pzn-sales-status-code";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(
        this Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode value
    ) =>
        value switch
        {
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.D => "D",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.F => "F",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.N => "N",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.R => "R",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.Z => "Z",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(
        this Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode value
    ) =>
        value switch
        {
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.D => "Wegfall",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.F => "Außer Vertrieb",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.N => "Im Vertrieb",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.R => "Rückruf",
            Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.Z => "Zurückgezogen",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(
        this Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode value
    ) => new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode"/>, or <c>null</c> if none matches.</returns>
    public static Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode? FromValue(
        string code
    ) =>
        code switch
        {
            "D" => Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.D,
            "F" => Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.F,
            "N" => Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.N,
            "R" => Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.R,
            "Z" => Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode.Z,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Medikation.CodeSystems.MiiCsMedikationPznSalesStatusCode FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for <see cref="Medikation.CodeSystems.MiiCsMedikationWirkstofftyp"/>.</summary>
public static class MiiCsMedikationWirkstofftypExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp</c>.</returns>
    public static string Url(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp _) =>
        "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp value) =>
        value switch
        {
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.In => "IN",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.Pin => "PIN",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.Min => "MIN",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp value) =>
        value switch
        {
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.In => "ingredient",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.Pin => "precise ingredient",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.Min => "multiple ingredients",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Medikation.CodeSystems.MiiCsMedikationWirkstofftyp"/>, or <c>null</c> if none matches.</returns>
    public static Medikation.CodeSystems.MiiCsMedikationWirkstofftyp? FromValue(string code) =>
        code switch
        {
            "IN" => Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.In,
            "PIN" => Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.Pin,
            "MIN" => Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.Min,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Medikation.CodeSystems.MiiCsMedikationWirkstofftyp"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Medikation.CodeSystems.MiiCsMedikationWirkstofftyp FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for reading <see cref="Medikation.Extensions"/> from FHIR resources.</summary>
public static class MedikationFhirExtensions
{
    /// <summary>Gets the extension <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Extension? GetMiiExMedikationWirkstoffrelation(this IExtendable resource) =>
        resource.GetExtension(
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation"
        );

    /// <summary>Gets the value of extension <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static Coding? GetMiiExMedikationWirkstofftyp(this IExtendable resource) =>
        resource.GetExtensionValue<Coding>(
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp"
        );
}
