// Generated by ig-codegen from de.medizininformatikinitiative.kerndatensatz.medikation 2026.0.1. Do not edit directly.
using Hl7.Fhir.Model;

namespace De.Medizininformatikinitiative.Kerndatensatz.Medikation;

public static class Medikation
{
    public static class CodeSystems
    {
        public static class Urls
        {
            /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp</c>.</summary>
            public static string MiiCsMedikationWirkstofftyp =>
                "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp";
        }

        /// <summary>Concepts for <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp</c>.</summary>
        public enum MiiCsMedikationWirkstofftyp
        {
            /// <summary><c>IN</c> - ingredient</summary>
            IN,

            /// <summary><c>PIN</c> - precise ingredient</summary>
            PIN,

            /// <summary><c>MIN</c> - multiple ingredients</summary>
            MIN,
        }
    }

    public static class Profiles
    {
        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1</c>.</summary>
        public static string MiiPrMedikationMedication =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication|2026.0.1";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1</c>.</summary>
        public static string MiiPrMedikationMedicationAdministration =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration|2026.0.1";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1</c>.</summary>
        public static string MiiPrMedikationMedicationRequest =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest|2026.0.1";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1</c>.</summary>
        public static string MiiPrMedikationMedicationStatement =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement|2026.0.1";

        /// <summary>The canonical URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1</c>.</summary>
        public static string MiiPrMedikationMedikationsliste =>
            "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste|2026.0.1";
    }

    public static class Extensions
    {
        /// <summary>
        /// A new, empty <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation</c>, for further
        /// population with nested extensions via <see cref="Extension.AddExtension"/>.
        /// </summary>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation</c> and no value.</returns>
        public static Extension MiiExMedikationWirkstoffrelation() =>
            new()
            {
                Url =
                    "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstoffrelation",
            };

        /// <summary>A new <see cref="Extension"/> for <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp</c>.</summary>
        /// <param name="value">The extension value, as a <c>MiiCsMedikationWirkstofftyp</c> concept.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp</c> and the given value.</returns>
        public static Extension MiiExMedikationWirkstofftyp(
            CodeSystems.MiiCsMedikationWirkstofftyp value
        ) =>
            new(
                "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/wirkstofftyp",
                value.Coding()
            );
    }
}

/// <summary>Extension methods for <see cref="Medikation.CodeSystems.MiiCsMedikationWirkstofftyp"/>.</summary>
public static class MiiCsMedikationWirkstofftypExtensions
{
    /// <returns>The CodeSystem URL <c>https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp</c>.</returns>
    public static string Url(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp _) =>
        "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/CodeSystem/wirkstofftyp";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp value) =>
        value switch
        {
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.IN => "IN",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.PIN => "PIN",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.MIN => "MIN",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp value) =>
        value switch
        {
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.IN => "ingredient",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.PIN => "precise ingredient",
            Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.MIN => "multiple ingredients",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Medikation.CodeSystems.MiiCsMedikationWirkstofftyp value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Medikation.CodeSystems.MiiCsMedikationWirkstofftyp"/>, or <c>null</c> if none matches.</returns>
    public static Medikation.CodeSystems.MiiCsMedikationWirkstofftyp? FromValue(string code) =>
        code switch
        {
            "IN" => Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.IN,
            "PIN" => Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.PIN,
            "MIN" => Medikation.CodeSystems.MiiCsMedikationWirkstofftyp.MIN,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Medikation.CodeSystems.MiiCsMedikationWirkstofftyp"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Medikation.CodeSystems.MiiCsMedikationWirkstofftyp FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}
