package io.github.dizuker.igcodegen;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.lang.model.element.Modifier;

/**
 * Renders an {@link IgPackageModel} as a Java source file: one utility class per non-empty category
 * (CodeSystems/Profiles/Extensions), each holding one static no-arg accessor method per canonical
 * URL, named in record-accessor style (lowerCamelCase, no {@code get} prefix).
 *
 * <p>E.g. the FHIR id {@code mii-pr-diagnose-condition} becomes the accessor {@code
 * miiPrDiagnoseCondition()}, called as {@code Onkologie.Profiles.miiPrDiagnoseCondition()}.
 *
 * <p>A CodeSystem that ships its own concepts inline ({@code content == "complete"}) additionally
 * gets a nested enum, named after the CodeSystem itself, with one constant per concept, a {@code
 * coding()} accessor returning a HAPI {@code org.hl7.fhir.r4.model.Coding}, and a static {@code
 * fromValue(String)} lookup by {@code code}, e.g. {@code
 * Onkologie.CodeSystems.MiiCsOnkoIntention.K.coding()} and {@code
 * Onkologie.CodeSystems.MiiCsOnkoIntention.fromValue("K")}.
 */
public final class JavaConstantsGenerator {

  private static final ClassName CODING_TYPE = ClassName.get("org.hl7.fhir.r4.model", "Coding");
  private static final AnnotationSpec NONNULL =
      AnnotationSpec.builder(ClassName.get("org.jspecify.annotations", "NonNull")).build();
  private static final AnnotationSpec NULLABLE =
      AnnotationSpec.builder(ClassName.get("org.jspecify.annotations", "Nullable")).build();

  private JavaConstantsGenerator() {}

  public static JavaFile generate(IgPackageModel model, String javaPackageName, String className) {
    TypeSpec.Builder rootType =
        TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addMethod(privateConstructor());

    addAccessorClass(rootType, "CodeSystems", model.codeSystems(), model.codeSystemConcepts());
    addAccessorClass(rootType, "Profiles", model.profiles(), Map.of());
    addAccessorClass(rootType, "Extensions", model.extensions(), Map.of());

    return JavaFile.builder(javaPackageName, rootType.build())
        .addFileComment(
            "Generated by ig-codegen from $L $L. Do not edit directly.",
            model.packageName(),
            model.packageVersion())
        .build();
  }

  public static Path writeTo(
      IgPackageModel model, String javaPackageName, String className, Path outputDir)
      throws IOException {
    JavaFile javaFile = generate(model, javaPackageName, className);
    javaFile.writeTo(outputDir);
    return outputDir.resolve(javaPackageName.replace('.', '/')).resolve(className + ".java");
  }

  private static void addAccessorClass(
      TypeSpec.Builder rootType,
      String nestedClassName,
      Map<String, String> constants,
      Map<String, List<ConceptConstant>> conceptsByName) {
    if (constants.isEmpty()) {
      return;
    }

    TypeSpec.Builder nestedType =
        TypeSpec.classBuilder(nestedClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .addMethod(privateConstructor());
    for (Map.Entry<String, String> entry : constants.entrySet()) {
      String url = entry.getValue();
      String accessorName = NameUtils.toCamelCase(entry.getKey());
      nestedType.addMethod(
          MethodSpec.methodBuilder(accessorName)
              .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
              .addJavadoc("The canonical URL {@code $L}.\n\n@return {@code $L}\n", url, url)
              .returns(String.class)
              .addStatement("return $S", url)
              .build());

      List<ConceptConstant> concepts = conceptsByName.get(entry.getKey());
      if (concepts != null && !concepts.isEmpty()) {
        nestedType.addType(buildConceptEnum(NameUtils.toPascalCase(entry.getKey()), url, concepts));
      }
    }
    rootType.addType(nestedType.build());
  }

  private static TypeSpec buildConceptEnum(
      String enumName, String system, List<ConceptConstant> concepts) {
    ClassName selfType = ClassName.get("", enumName);
    TypeSpec.Builder enumType =
        TypeSpec.enumBuilder(enumName)
            .addModifiers(Modifier.PUBLIC)
            .addField(
                FieldSpec.builder(
                        ClassName.get(String.class).annotated(NONNULL),
                        "code",
                        Modifier.PRIVATE,
                        Modifier.FINAL)
                    .build())
            .addField(
                FieldSpec.builder(
                        ClassName.get(String.class).annotated(NULLABLE),
                        "display",
                        Modifier.PRIVATE,
                        Modifier.FINAL)
                    .build())
            .addMethod(
                MethodSpec.constructorBuilder()
                    .addParameter(
                        ParameterSpec.builder(
                                ClassName.get(String.class).annotated(NONNULL), "code")
                            .build())
                    .addParameter(
                        ParameterSpec.builder(
                                ClassName.get(String.class).annotated(NULLABLE), "display")
                            .build())
                    .addStatement("this.code = code")
                    .addStatement("this.display = display")
                    .build())
            .addMethod(
                MethodSpec.methodBuilder("coding")
                    .addModifiers(Modifier.PUBLIC)
                    .returns(CODING_TYPE.annotated(NONNULL))
                    .addJavadoc(
                        "@return a new {@link Coding} for this concept, with system {@code $L}\n",
                        system)
                    .addStatement("return new $T($S, code, display)", CODING_TYPE, system)
                    .build())
            .addMethod(
                MethodSpec.methodBuilder("fromValue")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .addParameter(
                        ParameterSpec.builder(
                                ClassName.get(String.class).annotated(NONNULL), "code")
                            .build())
                    .returns(
                        ParameterizedTypeName.get(
                            ClassName.get(Optional.class), selfType.annotated(NONNULL)))
                    .addJavadoc(
                        """
                        @param code the FHIR code to look up
                        @return an {@link Optional} containing the constant whose {@code code} matches, or empty if none matches
                        """)
                    .beginControlFlow("for ($T value : values())", selfType)
                    .beginControlFlow("if (value.code.equals(code))")
                    .addStatement("return $T.of(value)", Optional.class)
                    .endControlFlow()
                    .endControlFlow()
                    .addStatement("return $T.empty()", Optional.class)
                    .build());

    for (ConceptConstant concept : concepts) {
      enumType.addEnumConstant(
          concept.constantName(),
          TypeSpec.anonymousClassBuilder("$S, $S", concept.code(), concept.display()).build());
    }
    return enumType.build();
  }

  private static MethodSpec privateConstructor() {
    return MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build();
  }
}
