package io.github.dizuker.igcodegen;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import java.io.IOException;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.lang.model.element.Modifier;

/**
 * Renders an {@link IgPackageModel} as a Java source file: one utility class per non-empty category
 * (CodeSystems/Profiles/Extensions).
 *
 * <p>CodeSystems and Profiles each get one static no-arg accessor method per canonical URL, named
 * in record-accessor style (lowerCamelCase, no {@code get} prefix). E.g. the FHIR id {@code
 * mii-pr-diagnose-condition} becomes the accessor {@code miiPrDiagnoseCondition()}, called as
 * {@code Onkologie.Profiles.miiPrDiagnoseCondition()}.
 *
 * <p>A CodeSystem that ships its own concepts inline ({@code content == "complete"}) additionally
 * gets a nested enum, named after the CodeSystem itself, with one constant per concept, a {@code
 * coding()} accessor returning a HAPI {@code org.hl7.fhir.r4.model.Coding}, and a static {@code
 * fromValue(String)} lookup by {@code code}, e.g. {@code
 * Onkologie.CodeSystems.MiiCsOnkoIntention.K.coding()} and {@code
 * Onkologie.CodeSystems.MiiCsOnkoIntention.fromValue("K")}.
 *
 * <p>Extensions instead get a static factory method per canonical URL that returns a HAPI {@code
 * org.hl7.fhir.r4.model.Extension} missing only the value: a simple extension with a single {@code
 * value[x]} type takes that type as its {@code value} parameter (e.g. {@code CodeableConcept} for
 * {@code Extension.value[x]: CodeableConcept}), a choice-typed {@code value[x]} takes the generic
 * HAPI {@code Type}, and a complex extension (nested sub-extensions, no {@code value[x]} of its
 * own) takes no parameter at all, e.g. {@code Onkologie.Extensions.miiExOnkoOperationIntention(new
 * CodeableConcept(...))}.
 *
 * <p>If a {@code CodeableConcept}/{@code Coding}-typed {@code value[x]} additionally pins its
 * {@code Coding.system} to one fixed CodeSystem that ships its own concepts (see above), the
 * factory method takes that CodeSystem's generated enum directly instead of the generic datatype,
 * e.g. {@code Onkologie.Extensions.miiExOnkoStrahlentherapieIntention(MiiCsOnkoIntention.K)}.
 */
public final class JavaConstantsGenerator {

  private static final ClassName CODING_TYPE = ClassName.get("org.hl7.fhir.r4.model", "Coding");
  private static final ClassName CODEABLE_CONCEPT_TYPE =
      ClassName.get("org.hl7.fhir.r4.model", "CodeableConcept");
  private static final ClassName EXTENSION_TYPE =
      ClassName.get("org.hl7.fhir.r4.model", "Extension");
  private static final ClassName GENERIC_VALUE_TYPE =
      ClassName.get("org.hl7.fhir.r4.model", "Type");
  private static final AnnotationSpec NONNULL =
      AnnotationSpec.builder(ClassName.get("org.jspecify.annotations", "NonNull")).build();
  private static final AnnotationSpec NULLABLE =
      AnnotationSpec.builder(ClassName.get("org.jspecify.annotations", "Nullable")).build();

  private JavaConstantsGenerator() {}

  public static JavaFile generate(IgPackageModel model, String javaPackageName, String className) {
    TypeSpec.Builder rootType =
        TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addMethod(privateConstructor());

    addAccessorClass(rootType, "CodeSystems", model.codeSystems(), model.codeSystemConcepts());
    addAccessorClass(rootType, "Profiles", model.profiles(), Map.of());
    addExtensionsClass(
        rootType,
        model.extensions(),
        model.extensionValueTypes(),
        boundEnumSimpleNamesByCodeSystemUrl(model));

    return JavaFile.builder(javaPackageName, rootType.build())
        .addFileComment(
            "Generated by ig-codegen from $L $L. Do not edit directly.",
            model.packageName(),
            model.packageVersion())
        .build();
  }

  public static Path writeTo(
      IgPackageModel model, String javaPackageName, String className, Path outputDir)
      throws IOException {
    JavaFile javaFile = generate(model, javaPackageName, className);
    javaFile.writeTo(outputDir);
    return outputDir.resolve(javaPackageName.replace('.', '/')).resolve(className + ".java");
  }

  private static void addAccessorClass(
      TypeSpec.Builder rootType,
      String nestedClassName,
      Map<String, String> constants,
      Map<String, List<ConceptConstant>> conceptsByName) {
    if (constants.isEmpty()) {
      return;
    }

    TypeSpec.Builder nestedType =
        TypeSpec.classBuilder(nestedClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .addMethod(privateConstructor());
    for (Map.Entry<String, String> entry : constants.entrySet()) {
      String url = entry.getValue();
      String accessorName = NameUtils.toCamelCase(entry.getKey());
      nestedType.addMethod(
          MethodSpec.methodBuilder(accessorName)
              .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
              .addJavadoc("The canonical URL {@code $L}.\n\n@return {@code $L}\n", url, url)
              .returns(String.class)
              .addStatement("return $S", url)
              .build());

      List<ConceptConstant> concepts = conceptsByName.get(entry.getKey());
      if (concepts != null && !concepts.isEmpty()) {
        nestedType.addType(buildConceptEnum(NameUtils.toPascalCase(entry.getKey()), url, concepts));
      }
    }
    rootType.addType(nestedType.build());
  }

  private static void addExtensionsClass(
      TypeSpec.Builder rootType,
      Map<String, String> extensions,
      Map<String, ExtensionValueType> extensionValueTypes,
      Map<String, String> boundEnumSimpleNamesByCodeSystemUrl) {
    if (extensions.isEmpty()) {
      return;
    }

    TypeSpec.Builder nestedType =
        TypeSpec.classBuilder("Extensions")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .addMethod(privateConstructor());
    for (Map.Entry<String, String> entry : extensions.entrySet()) {
      String url = entry.getValue();
      String accessorName = NameUtils.toCamelCase(entry.getKey());
      ExtensionValueType valueType =
          extensionValueTypes.getOrDefault(entry.getKey(), ExtensionValueType.NONE);
      nestedType.addMethod(
          buildExtensionFactoryMethod(
              accessorName, url, valueType, boundEnumSimpleNamesByCodeSystemUrl));
    }
    rootType.addType(nestedType.build());
  }

  /**
   * Maps each CodeSystem URL that has a generated concept enum (see {@link #buildConceptEnum}) to
   * that enum's simple name, so a bound {@code CodeableConcept}/{@code Coding} extension value (see
   * {@link ExtensionValueType#boundCodeSystemUrl}) can be typed to it instead of the generic
   * datatype.
   */
  private static Map<String, String> boundEnumSimpleNamesByCodeSystemUrl(IgPackageModel model) {
    Map<String, String> enumSimpleNamesByUrl = new HashMap<>();
    for (String constantName : model.codeSystemConcepts().keySet()) {
      String url = model.codeSystems().get(constantName);
      if (url != null) {
        enumSimpleNamesByUrl.put(url, NameUtils.toPascalCase(constantName));
      }
    }
    return enumSimpleNamesByUrl;
  }

  /**
   * Builds a static factory method returning a HAPI {@link Extension} for one canonical extension
   * URL, missing only the value: a no-arg overload returning {@code new Extension(url)} for a
   * complex extension with no {@code value[x]} of its own (see {@link ExtensionValueType#NONE}),
   * otherwise a single-{@code value}-parameter overload returning {@code new Extension(url,
   * value)}. The {@code value} parameter is typed to the extension's {@code value[x]} type if it
   * has exactly one (see {@link ExtensionValueType#fixed}) - or, if that type is a {@code
   * CodeableConcept}/{@code Coding} bound to a CodeSystem with a generated enum (see {@link
   * ExtensionValueType#boundCodeSystemUrl}), to that enum directly - or the generic HAPI {@code
   * Type} if {@code value[x]} is a choice of several (see {@link ExtensionValueType#CHOICE}).
   */
  private static MethodSpec buildExtensionFactoryMethod(
      String accessorName,
      String url,
      ExtensionValueType valueType,
      Map<String, String> boundEnumSimpleNamesByCodeSystemUrl) {
    MethodSpec.Builder method =
        MethodSpec.methodBuilder(accessorName)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(EXTENSION_TYPE.annotated(NONNULL));

    if (valueType.fhirTypeCode() == null && !valueType.choice()) {
      return method
          .addJavadoc(
              """
              A new, empty {@link Extension} for the canonical URL {@code $L}, for further
              population with nested extensions via {@link Extension#addExtension}.

              @return a new {@link Extension} with url {@code $L} and no value
              """,
              url,
              url)
          .addStatement("return new $T($S)", EXTENSION_TYPE, url)
          .build();
    }

    String boundEnumSimpleName =
        valueType.boundCodeSystemUrl() == null
            ? null
            : boundEnumSimpleNamesByCodeSystemUrl.get(valueType.boundCodeSystemUrl());
    if (boundEnumSimpleName != null) {
      return buildBoundCodingExtensionFactoryMethod(
          method, url, Objects.requireNonNull(valueType.fhirTypeCode()), boundEnumSimpleName);
    }

    ClassName valueClassName =
        valueType.choice()
            ? GENERIC_VALUE_TYPE
            : hapiTypeFor(Objects.requireNonNull(valueType.fhirTypeCode()));
    return method
        .addParameter(ParameterSpec.builder(valueClassName.annotated(NONNULL), "value").build())
        .addJavadoc(
            """
            A new {@link Extension} for the canonical URL {@code $L}.

            @param value the extension value
            @return a new {@link Extension} with url {@code $L} and the given value
            """,
            url,
            url)
        .addStatement("return new $T($S, value)", EXTENSION_TYPE, url)
        .build();
  }

  /**
   * Builds the factory method overload for a {@code CodeableConcept}/{@code Coding} extension value
   * whose {@code Coding.system} is pinned to a CodeSystem with a generated concept enum: the {@code
   * value} parameter takes that enum directly, and the method body converts it via the enum's
   * {@code coding()} accessor - wrapped in a new {@link CodeableConcept} if that's the extension's
   * value type.
   */
  private static MethodSpec buildBoundCodingExtensionFactoryMethod(
      MethodSpec.Builder method, String url, String fhirTypeCode, String boundEnumSimpleName) {
    ClassName enumType = ClassName.get("", "CodeSystems", boundEnumSimpleName);
    method
        .addParameter(ParameterSpec.builder(enumType.annotated(NONNULL), "value").build())
        .addJavadoc(
            """
            A new {@link Extension} for the canonical URL {@code $L}.

            @param value the extension value, as a {@code $L} concept
            @return a new {@link Extension} with url {@code $L} and the given value
            """,
            url,
            boundEnumSimpleName,
            url);
    if ("CodeableConcept".equals(fhirTypeCode)) {
      return method
          .addStatement(
              "return new $T($S, new $T(value.coding()))",
              EXTENSION_TYPE,
              url,
              CODEABLE_CONCEPT_TYPE)
          .build();
    }
    return method.addStatement("return new $T($S, value.coding())", EXTENSION_TYPE, url).build();
  }

  /**
   * Maps a FHIR type code (e.g. {@code "CodeableConcept"}, {@code "string"}) to its HAPI R4 model
   * class name: complex types keep their name as-is, primitive types (identified by a lowercase
   * first letter, per FHIR convention) get capitalized with a {@code Type} suffix (e.g. {@code
   * "string"} -> {@code StringType}, {@code "dateTime"} -> {@code DateTimeType}).
   */
  private static ClassName hapiTypeFor(String fhirTypeCode) {
    String hapiClassName =
        Character.isLowerCase(fhirTypeCode.charAt(0))
            ? Character.toUpperCase(fhirTypeCode.charAt(0)) + fhirTypeCode.substring(1) + "Type"
            : fhirTypeCode;
    return ClassName.get("org.hl7.fhir.r4.model", hapiClassName);
  }

  private static TypeSpec buildConceptEnum(
      String enumName, String system, List<ConceptConstant> concepts) {
    ClassName selfType = ClassName.get("", enumName);
    TypeSpec.Builder enumType =
        TypeSpec.enumBuilder(enumName)
            .addModifiers(Modifier.PUBLIC)
            .addField(
                FieldSpec.builder(
                        ClassName.get(String.class).annotated(NONNULL),
                        "code",
                        Modifier.PRIVATE,
                        Modifier.FINAL)
                    .build())
            .addField(
                FieldSpec.builder(
                        ClassName.get(String.class).annotated(NULLABLE),
                        "display",
                        Modifier.PRIVATE,
                        Modifier.FINAL)
                    .build())
            .addMethod(
                MethodSpec.constructorBuilder()
                    .addParameter(
                        ParameterSpec.builder(
                                ClassName.get(String.class).annotated(NONNULL), "code")
                            .build())
                    .addParameter(
                        ParameterSpec.builder(
                                ClassName.get(String.class).annotated(NULLABLE), "display")
                            .build())
                    .addStatement("this.code = code")
                    .addStatement("this.display = display")
                    .build())
            .addMethod(
                MethodSpec.methodBuilder("coding")
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(
                        ParameterSpec.builder(selfType.annotated(NONNULL), "this").build())
                    .returns(CODING_TYPE.annotated(NONNULL))
                    .addJavadoc(
                        "@return a new {@link Coding} for this concept, with system {@code $L}\n",
                        system)
                    .addStatement("return new $T($S, code, display)", CODING_TYPE, system)
                    .build())
            .addMethod(
                MethodSpec.methodBuilder("fromValue")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .addParameter(
                        ParameterSpec.builder(
                                ClassName.get(String.class).annotated(NONNULL), "code")
                            .build())
                    .returns(
                        ParameterizedTypeName.get(
                            ClassName.get(Optional.class), selfType.annotated(NONNULL)))
                    .addJavadoc(
                        """
                        @param code the FHIR code to look up
                        @return an {@link Optional} containing the constant whose {@code code} matches, or empty if none matches
                        """)
                    .beginControlFlow("for ($T value : values())", selfType)
                    .beginControlFlow("if (value.code.equals(code))")
                    .addStatement("return $T.of(value)", Optional.class)
                    .endControlFlow()
                    .endControlFlow()
                    .addStatement("return $T.empty()", Optional.class)
                    .build());

    for (ConceptConstant concept : concepts) {
      TypeSpec.Builder constant =
          TypeSpec.anonymousClassBuilder("$S, $S", concept.code(), concept.display());
      if (concept.display() != null) {
        constant.addJavadoc("{@code $L} - $L\n", concept.code(), concept.display());
      } else {
        constant.addJavadoc("{@code $L}\n", concept.code());
      }
      enumType.addEnumConstant(concept.constantName(), constant.build());
    }
    return enumType.build();
  }

  private static MethodSpec privateConstructor() {
    return MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build();
  }
}
