using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Dizuker.IgCodegen;

/// <summary>
/// Renders an <see cref="IgPackageModel"/> as a C# source file, built as a Roslyn syntax tree via
/// <see cref="Microsoft.CodeAnalysis.CSharp.SyntaxFactory"/> (the closest C# equivalent of
/// JavaPoet) and pretty-printed with Roslyn's own <see cref="Formatter"/> - no external formatter
/// binary needed.
///
/// <para>One nested static class per non-empty category (CodeSystems/Profiles/Extensions), each
/// holding one static property per canonical URL, named in PascalCase (e.g. the FHIR id
/// <c>mii-pr-diagnose-condition</c> becomes the property <c>MiiPrDiagnoseCondition</c>, accessed
/// as <c>Onkologie.Profiles.MiiPrDiagnoseCondition</c>).</para>
///
/// <para>A CodeSystem that ships its own concepts inline (<c>content == "complete"</c>) gets a
/// nested static class instead of a plain URL property - named after the CodeSystem itself, with
/// one <see cref="Hl7.Fhir.Model.Coding"/>-returning property per concept and a static
/// <c>FromValue(code)</c> lookup, e.g. <c>Onkologie.CodeSystems.MiiCsOnkoIntention.K</c> and
/// <c>Onkologie.CodeSystems.MiiCsOnkoIntention.FromValue("K")</c>.</para>
/// </summary>
public static class CSharpConstantsGenerator
{
    public static string Generate(IgPackageModel model, string @namespace, string className)
    {
        var categories = new[]
        {
            BuildCategoryClass("CodeSystems", model.CodeSystems, model.CodeSystemConcepts),
            BuildCategoryClass("Profiles", model.Profiles, null),
            BuildCategoryClass("Extensions", model.Extensions, null),
        };
        var nonEmptyCategories = categories.Where(c => c is not null).Select(c => c!).ToList();
        bool hasAnyConceptClass = model.CodeSystemConcepts.Count > 0;

        ClassDeclarationSyntax outerClass = ClassDeclaration(className)
            .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
            .WithMembers(List<MemberDeclarationSyntax>(nonEmptyCategories));

        var namespaceDecl = FileScopedNamespaceDeclaration(ParseName(@namespace))
            .WithMembers(SingletonList<MemberDeclarationSyntax>(outerClass));

        SyntaxList<UsingDirectiveSyntax> usings = hasAnyConceptClass
            ? SingletonList(UsingDirective(ParseName("Hl7.Fhir.Model")))
            : default;

        CompilationUnitSyntax compilationUnit = CompilationUnit()
            .WithUsings(usings)
            .WithMembers(SingletonList<MemberDeclarationSyntax>(namespaceDecl))
            .WithLeadingTrivia(
                Comment($"// Generated by ig-codegen from {model.PackageName} {model.PackageVersion}. Do not edit directly."),
                CarriageReturnLineFeed);

        return Format(compilationUnit);
    }

    public static string WriteTo(IgPackageModel model, string @namespace, string className, string outputFile)
    {
        string? directory = Path.GetDirectoryName(outputFile);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }
        File.WriteAllText(outputFile, Generate(model, @namespace, className));
        return outputFile;
    }

    private static ClassDeclarationSyntax? BuildCategoryClass(
        string categoryName,
        IReadOnlyDictionary<string, string> constants,
        IReadOnlyDictionary<string, List<ConceptConstant>>? conceptsByName)
    {
        if (constants.Count == 0)
        {
            return null;
        }

        var members = new List<MemberDeclarationSyntax>();
        foreach ((string constantName, string url) in constants)
        {
            List<ConceptConstant>? concepts = conceptsByName?.GetValueOrDefault(constantName);
            string propertyName = NameUtils.ToPropertyCase(constantName);
            if (concepts is { Count: > 0 })
            {
                members.Add(BuildConceptsClass(propertyName, url, concepts));
            }
            else
            {
                members.Add(BuildUrlProperty(propertyName, url));
            }
        }

        return ClassDeclaration(categoryName)
            .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
            .WithMembers(List(members));
    }

    private static PropertyDeclarationSyntax BuildUrlProperty(string propertyName, string url)
    {
        return PropertyDeclaration(PredefinedType(Token(SyntaxKind.StringKeyword)), propertyName)
            .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
            .WithExpressionBody(ArrowExpressionClause(StringLiteral(url)))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(DocComment("<summary>", $"The canonical URL <c>{url}</c>.", "</summary>"));
    }

    private static ClassDeclarationSyntax BuildConceptsClass(string className, string url, List<ConceptConstant> concepts)
    {
        var members = new List<MemberDeclarationSyntax>
        {
            FieldDeclaration(
                    VariableDeclaration(PredefinedType(Token(SyntaxKind.StringKeyword)))
                        .WithVariables(SingletonSeparatedList(
                            VariableDeclarator("Url").WithInitializer(EqualsValueClause(StringLiteral(url))))))
                .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.ConstKeyword))),
        };

        foreach (ConceptConstant concept in concepts)
        {
            members.Add(
                PropertyDeclaration(ParseTypeName("Coding"), concept.PropertyName)
                    .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                    .WithExpressionBody(ArrowExpressionClause(ParseExpression(
                        $"new(Url, {StringLiteral(concept.Code)}, {NullableStringLiteralText(concept.Display)})")))
                    .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)));
        }

        members.Add(
            PropertyDeclaration(
                    GenericName("IEnumerable").WithTypeArgumentList(
                        TypeArgumentList(SingletonSeparatedList<TypeSyntax>(ParseTypeName("Coding")))),
                    "All")
                .WithModifiers(TokenList(Token(SyntaxKind.PrivateKeyword), Token(SyntaxKind.StaticKeyword)))
                .WithExpressionBody(ArrowExpressionClause(
                    ParseExpression("new[] { " + string.Join(", ", concepts.Select(c => c.PropertyName)) + " }")))
                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)));

        members.Add(
            MethodDeclaration(ParseTypeName("Coding"), "FromValue")
                .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
                .WithParameterList(ParameterList(SingletonSeparatedList(
                    Parameter(Identifier("code")).WithType(PredefinedType(Token(SyntaxKind.StringKeyword))))))
                .WithExpressionBody(ArrowExpressionClause(ParseExpression(
                    "All.FirstOrDefault(c => c.Code == code) ?? throw new ArgumentException($\"Unknown code: {code}\")")))
                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
                .WithLeadingTrivia(DocComment(
                    "<summary>",
                    "Looks up the constant whose <c>Code</c> equals <paramref name=\"code\"/>.",
                    "</summary>",
                    "<param name=\"code\">the FHIR code to look up</param>",
                    "<returns>the matching <see cref=\"Coding\"/></returns>",
                    "<exception cref=\"ArgumentException\">if no constant has that code</exception>")));

        return ClassDeclaration(className)
            .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword)))
            .WithMembers(List(members));
    }

    private static LiteralExpressionSyntax StringLiteral(string value) =>
        LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value));

    private static string NullableStringLiteralText(string? value) =>
        value is null ? "null" : StringLiteral(value).ToFullString();

    private static SyntaxTriviaList DocComment(params string[] lines) =>
        TriviaList(lines.SelectMany(line => new[] { Comment("/// " + line), CarriageReturnLineFeed }));

    private static string Format(CompilationUnitSyntax compilationUnit)
    {
        using var workspace = new AdhocWorkspace();
        SyntaxNode formatted = Formatter.Format(compilationUnit, workspace);
        return formatted.ToFullString();
    }
}
